### ISSUE TITLE
sometimes, dispatcher responds with "job_status:submitted" when request (from frontend) had query_status:ready

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#101]
it's not very clear  why it happens, it used happened before - for years.
after several cycles of this behavior the result is returned, but it's a bit confusing for the user.

**Comment by volodymyrss** [comment]
I realized that this also results in a large set of emails being sent.

**Comment by volodymyrss** [comment]
maybe one mitigation could be to track submitted emails in dispatcher session state, and prevent multiple "submitted" ones?

**Comment by burnout87** [comment]
> maybe one mitigation could be to track submitted emails in dispatcher session state, and prevent multiple "submitted" ones?

Track the last email with `submitted` so as to know at what time this was sent, and in case not enough time has passed, avoid sending another `submitted` one.

At the moment, does the dispatcher have the concept of session state?

**Comment by volodymyrss** [comment]
It has this scratch session/job directory, it tracks the state identified by session_id+job_id .

**Comment by burnout87** [comment]
Then we could add the time the last email with the `submitted` state was sent.

**Comment by volodymyrss** [comment]
Could we also just store all sent emails in that directory? It will help to keep track of what was sent to users.
And before sending check for files there.
Since we are using files for this, for now.

**Comment by burnout87** [comment]
Would it make sense to record the history of the emails sent directly within the query_output json file?

Or would it be more appropriate to use a dedicated file?

**Comment by volodymyrss** [comment]
query_output.json is preciesly query_output, as returned to the user, so unless we want to return total email list in there, with every request, it's not too useful.
Mail list is rather like a log file, so I'd keep it a separate file.
Could be even a separate file for each email, in a directory. It's similar to approach used for job statuses.
Actually that's how mails are kept in base linux system - as files in directories (no databases). 
It's a bit more thread-safe than updating single file.
But a single file is fine too, as you wish.
