### ISSUE TITLE
find example which reports warning

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#112]

**Comment by volodymyrss** [comment]
I did not find but I reproduced it:

![warning.png](https://images.zenhubusercontent.com/607479883b297d34d178c6c2/81ddcdaa-b198-47d2-9e96-4aace23e468f)

https://frontend.staging.odahub.io/cdci/astrooda/?DEC=-41.593417&RA=257.815417&T1=2003-03-15T23%3A27%3A40.0&T2=2003-03-16T00%3A03%3A15.0&T_format=isot&instrument=spi_acs&product_type=spi_acs_lc&query_status=new&query_type=Real&src_name=4U+1700-377&time_bin=2

There are many exit message fields used in somewhat convoluted way, I will describe the response schema:

https://github.com/oda-hub/dispatcher-app/pull/117

**Comment by volodymyrss** [comment]
I should have said directly that this "warning" is written in "exit_status.comment" and only shown if query is successful.

**Comment by volodymyrss** [comment]
@dsavchenko  this is FYI

**Comment by dsavchenko** [comment]
Thanks!

**Comment by dsavchenko** [comment]
btw, I get 403 from this frontend deployment

**Comment by volodymyrss** [comment]
like, always? Did something change?

**Comment by volodymyrss** [comment]
always or on calls from frontend to dispatcher?

**Comment by dsavchenko** [comment]
Always. It is github validation

**Comment by volodymyrss** [comment]
ah ok. I will add later.

This is dev instance of Mohamed, same dispatcher, it also shoes this message http://cdcidev.mtmco.net/cdci/astrooda/
