### ISSUE TITLE
consider what we as users and stakeholders want to see in the email

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#113]
I suggest something with instructive title (job status, basic job info - product type), possibly HTML link in the text.

e.g.

`[ ODA ] [ done ] in 1h10m isgri_image request from 2021-05-18T20:00`

 [ done ] in 1h10m isgri_image request from 2021-05-18T20:00

please follow the [link] to inspect the results.

**Comment by volodymyrss** [comment]
I think we should not focus on this now.

**Comment by burnout87** [comment]
I remember we already discussed about this here:

[https://github.com/oda-hub/dispatcher-app/issues/61#issuecomment-825672902](https://github.com/oda-hub/dispatcher-app/issues/61#issuecomment-825672902)

**Comment by volodymyrss** [comment]
indeed, we to quote a summary there we can make a template with jinja2 (bundled with flask).
Even for now, I would would at least change subject

**Comment by burnout87** [comment]
This is my idea for a more informative email subject

`[ODA 'osa_version'] Status update for the request 'job_id'`

Is the job_id a good way to identify the request?

**Comment by volodymyrss** [comment]
job_id is good.

osa version - I am not sure.
New status is most interesting. Also product name. And maybe time:

[ ODA ] [ {{ new_status }} ] request for {{ product_name }} created {{ time_created_isot }}

**Comment by burnout87** [comment]
> job_id is good.
> 
> osa version - I am not sure.
> New status is most interesting. Also product name. And maybe time:
> 
> [ ODA ] [ {{ new_status }} ] request for {{ product_name }} created {{ time_created_isot }} {{ job_id[:8] }}
> 
> maybe shorter version of job id (it's still unique), and full job id in text.

Agree, but I would just avoid the time of the request, might be not that necessary in the subject, it will be anyway part of the body of the email.

**Comment by volodymyrss** [comment]
What I as a user want to see in the subject is if it's something I was waiting for while, or a relatively short request. Either submission, or time elapsed since submission is something I want to learn immediately from subject.

**Comment by burnout87** [comment]
#16 provides a first implementation

**Comment by volodymyrss** [comment]
you mean #116
