### ISSUE TITLE
token should appear in the returned API code

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#118]
It must have disappeared due to the filtering applied.
It should remain in the API code, like we saw recently, but not in URLs.

Could this be adjusted?

**Comment by burnout87** [comment]
Is there some specific case where this happens? 

Because I run some tests but I could see that the token is still there in the API code.

**Comment by volodymyrss** [comment]
Hm. I can see it now. Maybe I just looked on public request! Or maybe something else. Can not reproduce, hence close.
