### ISSUE TITLE
second "submitted" message should be maybe called "resubmitted". multiple "done" avoided.

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#126]
The link in the first message is useful to check job status.
But then it leads to another "submitted".
This could be avoided.

**Comment by volodymyrss** [comment]
also "done" may happen multiple times, unnecessary.

**Comment by burnout87** [comment]
> also "done" may happen multiple times, unnecessary.

I am actually surprised this happens...once the request is completed, then that should be the end of it, right?

**Comment by ferrigno** [comment]
see https://github.com/oda-hub/doc-review-guidelines/issues/21 I am receiving an email every 2-3 minutes which ways done, but it is NOT as the API is still running.

**Comment by volodymyrss** [comment]
API is resubmitting requests, rather stop it then. It may have something to do with OSA11, could you try with OSA10.2

**Comment by volodymyrss** [comment]
the job is actually failing due to peculiarity of effects of the hardware issues. it will be better with OSA10. why is failing interpretted as done is unclear

**Comment by ferrigno** [comment]
OK, so this revealed another issue.

I submitted with OSA10.2, but less scws 

[ODA][submitted] Request for isgri_spectrum created at 2021-05-21 13:39:10 53f4bf33

Update of the task submitted at 2021-05-21 13:39:10, for the instrument isgri:

    status submitted

Products url https://www.astro.unige.ch/cdci/astrooda_?osa_version=OSA10.2&RA=275.09142677&DEC=7.18535523&radius=8&T1=58193.455&T2=58246.892&T_format=mjd&max_pointings=50&selected_catalog=%7B%22cat_frame%22%3A+%22fk5%22%2C+%22cat_coord_units%22%3A+%22deg%22%2C+%22cat_column_list%22%3A+%5B%5B17%2C+87%5D%2C+%5B%22GRS+1915%2B105%22%2C+%22MAXI+J1820%2B070%22%5D%2C+%5B29.396455764770508%2C+1803.1607666015625%5D%2C+%5B288.799560546875%2C+275.0911865234375%5D%2C+%5B10.939922332763672%2C+7.185144901275635%5D%2C+%5B-32768%2C+-32768%5D%2C+%5B2%2C+2%5D%2C+%5B0%2C+0%5D%2C+%5B0.0002800000074785203%2C+0.00041666667675599456%5D%5D%2C+%22cat_column_names%22%3A+%5B%22meta_ID%22%2C+%22src_names%22%2C+%22significance%22%2C+%22ra%22%2C+%22dec%22%2C+%22NEW_SOURCE%22%2C+%22ISGRI_FLAG%22%2C+%22FLAG%22%2C+%22ERR_RAD%22%5D%2C+%22cat_column_descr%22%3A+%5B%5B%22meta_ID%22%2C+%22%3 Ci8%22%5D%2C+%5B%22src_names%22%2C+%22%3CU20%22%5D%2C+%5B%22significance%22%2C+%22%3Cf8%22%5D%2C+%5B%22ra%22%2C+%22%3Cf8%22%5D%2C+%5B%22dec%22%2C+%22%3Cf8%22%5D%2C+%5B%22NEW_SOURCE%22%2C+%22%3Ci8%22%5D%2C+%5B%22ISGRI_FLAG%22%2C+%22%3Ci8%22%5D%2C+%5B%22FLAG%22%2C+%22%3Ci8%22%5D%2C+%5B%22ERR_RAD%22%2C+%22%7CO%22%5D%5D%2C+%22cat_lat_name%22%3A+%22dec%22%2C+%22cat_lon_name%22%3A+%22ra%22%7D&instrument=isgri&product_type=isgri_spectrum&query_type=Real&off_line=False&query_status=new&dry_run=False&api=True&oda_api_version=1.1.10&user_catalog_file=None

**Comment by volodymyrss** [comment]
> > also "done" may happen multiple times, unnecessary.
> 
> I am actually surprised this happens...once the request is completed, then that should be the end of it, right?

it has actually failed in a way that prevented correct message being sent. Nothing dispatcher could have known.
But, multiple "done" should be detected. And there is mechanism for that, right?

**Comment by burnout87** [comment]
Do we really want a `resubmitted` status?

**Comment by volodymyrss** [comment]
whenever the need for this happens special treatment is needed, sine this only happens in special and and unexpected cases. so I suggest to call it resubmitted or something similar. we can discuss tomorrow.
