### ISSUE TITLE
strange additional job is generated during some requests

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#137]
@ferrigno  reported in here experience: 
![119674165-416e6080-be3c-11eb-8199-15bd1291a98a](https://user-images.githubusercontent.com/3909535/119681303-3d454180-be42-11eb-9d13-f6e5519a9823.png)
https://github.com/oda-hub/doc-review-guidelines/issues/24

two job_id were generated

the good one, which was communicated to backend and eventually completed: eccf4011778bd97f
```
INFO:[ InstrumentQueryBackEnd : instrument-not-set ]:---> GENERATING JOB ID <---
INFO:[ InstrumentQueryBackEnd : instrument-not-set ]:---> new job id for {'osa_version': 'OSA11.0', 'radius': '8', 'RA': '275.09142677', 'DEC': '7.18535523', 'T1': '58193.455', 'T2': '58246.
892', 'T_format': 'mjd', 'max_pointings': '10', 'E1_keV': '30.0', 'E2_keV': '80.0', 'token': '', 'instrument': 'isgri', 'product_type': 'isgri_image', 'query_type': 'Real', 'off_line': 'False', 'que
ry_status': 'new', 'session_id': 'WKZ8SMLOWBJK6E2K', 'dry_run': 'False', 'api': 'True', 'oda_api_version': '1.1.11'} <---
INFO:[ InstrumentQueryBackEnd : instrument-not-set ]:generated NEW job_id eccf4011778bd97f
```

```
INFO:[ InstrumentQueryBackEnd : instrument-not-set ]:---> GENERATING JOB ID <---
INFO:[ InstrumentQueryBackEnd : instrument-not-set ]:---> new job id for {'src_name': '4U 1700-377', 'RA': '257.815417', 'DEC': '-41.593417', 'T1': '58195.455', 'T2': '58195.555', 'T_format'
: 'mjd', 'time_bin': '1', 'token': '', 'instrument': 'spi_acs', 'product_type': 'spi_acs_lc', 'query_type': 'Real', 'off_line': 'False', 'query_status': 'new', 'session_id': 'CGXGYMWRWDZDGQG1', 'dry
_run': 'False', 'api': 'True', 'oda_api_version': '1.1.11'} <---
INFO:[ InstrumentQueryBackEnd : instrument-not-set ]:generated NEW job_id 6e99264cc7f57896
```

**Comment by burnout87** [comment]
At first glance, those two are using two different `instrument` as well as two different `product_type`. So, this might explain why we have two different `job_id`

**Comment by volodymyrss** [comment]
notebook provided by @ferrigno gives details https://github.com/volodymyrss/oda-test-app/blob/master/Authentication.ipynb
e.g. note how job id 6e99264cc7f57896 actually comes from the first, spi-acs, request. But then it appears again!
You can see it is coming from oda_api sent.
The solution from oda_api should be to always initiate creation of new job with get_product.
From dispatcher, it should actively refuse it.

**Comment by ferrigno** [comment]
The Issue presented again by adding an ISGRI light curve request. Cannot upload the Notebook to the repository.
<pre>
#We get a light curve with 1000 s time bin and from 100 pointings (note that maximum is 500 !)
light_curve = disp.get_product(instrument="isgri", 
                 product="isgri_lc", 
                 product_type="Real", 
                 osa_version='OSA11.0',
                     RA=275.09142677,
                         DEC=7.18535523,
                    radius = 8,
                     T1=58193.455,
                         T2=58246.892,
                            E1_keV=30,
                            E2_keV=80,
                         T_format= 'mjd',
                     max_pointings=100,
                            time_bin=1000, #time bin in seconds
                     token=token,
                 selected_catalog=api_cat_str)
</pre>

**Comment by burnout87** [comment]
[https://github.com/burnout87/oda-test-app/blob/master/Authentication_27_05_2021.ipynb](https://github.com/burnout87/oda-test-app/blob/master/Authentication_27_05_2021.ipynb)

**Comment by volodymyrss** [comment]
please try with this https://github.com/oda-hub/oda_api/tree/auth-notebook

It happens in special case when multiple different requests are sent with the same DispatcherAPI object.
It does not immediately case an issue which can be easily spotted by the user.
No change in user behavior is needed here.

My fix to oda_api is changing an assumption on dispatcher communication, but I think it should work.
[this](https://github.com/oda-hub/dispatcher-app/issues/138) will make sure that dispatcher additionally resists this anomalous communication from oda_api.

**Comment by ferrigno** [comment]
The main request properly was done 
![image](https://user-images.githubusercontent.com/2527219/119794597-f43fcc80-bed7-11eb-870c-b1ce8834fab2.png)

**Comment by ferrigno** [comment]
> please try with this https://github.com/oda-hub/oda_api/tree/auth-notebook
> 
> It happens in special case when multiple different requests are sent with the same DispatcherAPI object.
> It does not immediately case an issue which can be easily spotted by the user.
> No change in user behavior is needed here.
> 
> My fix to oda_api is changing an assumption on dispatcher communication, but I think it should work.
> [this](https://github.com/oda-hub/dispatcher-app/issues/138) will make sure that dispatcher additionally resists this anomalous communication from oda_api.

Is it for me or Gabriele?

**Comment by volodymyrss** [comment]
> > please try with this https://github.com/oda-hub/oda_api/tree/auth-notebook
> > It happens in special case when multiple different requests are sent with the same DispatcherAPI object.
> > It does not immediately case an issue which can be easily spotted by the user.
> > No change in user behavior is needed here.
> > My fix to oda_api is changing an assumption on dispatcher communication, but I think it should work.
> > [this](https://github.com/oda-hub/dispatcher-app/issues/138) will make sure that dispatcher additionally resists this anomalous communication from oda_api.
> 
> Is it for me or Gabriele?

you @ferrigno  could try with this if the problem which you found before resolves:

try with this https://github.com/oda-hub/oda_api/tree/auth-notebook

**Comment by burnout87** [comment]
> please try with this https://github.com/oda-hub/oda_api/tree/auth-notebook
> 
> It happens in special case when multiple different requests are sent with the same DispatcherAPI object.
> It does not immediately case an issue which can be easily spotted by the user.
> No change in user behavior is needed here.
> 
> My fix to oda_api is changing an assumption on dispatcher communication, but I think it should work.
> [this](https://github.com/oda-hub/dispatcher-app/issues/138) will make sure that dispatcher additionally resists this anomalous communication from oda_api.

I was actually thinking about this behaviour that I also noticed while writing some tests, but thought I was doing something wrong indeed. When calling `get_product` without specifying a job_id, then the one used the first time is used

**Comment by burnout87** [comment]
To be closed I guess
