### ISSUE TITLE
if job_id is provided, and is not compatible with stored analysis_parameters.json, it should case 400 

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#138]

**Comment by volodymyrss** [comment]
does this make sense @burnout87 ?

**Comment by burnout87** [comment]
So an additional double-check should be included that performs a comparison between the provided job_id and the one calculate with the parameter. Yes it makes sense

**Comment by volodymyrss** [comment]
in a special case when job_id is provided. I am not too sure now why is it necessary to provide job_id along with parameters if job_id should be always calculated from it, but ok, let's not change it, else something may break.

**Comment by burnout87** [comment]
Something similar, though for a different purpose, has been implemented in here #156 

So I will implement an analogue approach
