### ISSUE TITLE
download_products does not work: disregard `instrument` request arg, verify token

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#147]

**Comment by volodymyrss** [comment]
Either one of us can fix address it. Probably just a simple condition is needed for the constructor.

It complains about a field it does not really need:

https://github.com/oda-hub/doc-review-guidelines/issues/27

**Comment by burnout87** [comment]
I have never used this functionality so I can take care of it

**Comment by burnout87** [comment]
Is it mainly called from the frontend?

**Comment by volodymyrss** [comment]
I think yes

**Comment by ferrigno** [comment]
I called it from frontend.

**Comment by volodymyrss** [comment]
Turns out it is issue number 1 in frontend:

https://github.com/oda-hub/frontend-astrooda/issues/1

I close this to avoid duplication.

**Comment by volodymyrss** [comment]
I commented on wrong issue. My bad.

**Comment by burnout87** [comment]
So, the problem is still within the frontend right?

**Comment by volodymyrss** [comment]
> So, the problem is still within the frontend right?

Not necessarily. 

This URL is generated by the frontend:

`https://frontend.staging.odahub.io/cdci/astrooda/dispatch-data/download_products?session_id=YET2L9Q9RQY6T9XM&file_list=query_spectrum_isgri_sum_Background.fits.gz.recovered,query_spectrum_arf_sum_Background.fits.gz.recovered,query_spectrum_rmf_sum_Background.fits.gz.recovered&download_file_name=spectra-Background.tar.gz&query_status=ready&job_id=50bcaf1e4c867a66&instrument=undefined`

It causes an issue in current dispatcher. It's easy to deduce that the issue is because of this `instrument=undefined`  at the end.

Replacing it with `instrument=isgri` works.

But, if you look on current public frontend:

`https://www.astro.unige.ch/cdci/astrooda/dispatch-data/download_products?session_id=UKAJHQ9WQ1Y82YPY&file_list=query_spectrum_isgri_sum_4U_1722-30.fits.gz,query_spectrum_arf_sum_4U_1722-30.fits.gz,query_spectrum_rmf_sum_4U_1722-30.fits.gz&download_file_name=spectra-4U%201722-30.tar.gz&query_status=ready&job_id=7158814916027144469&instrument=undefined`

same `instrument=undefined`, but dispatcher returns the result!

So I guess we made some sanity check or another use of `instrument` in the dispatcher, which lead to incorrecrly passed `instrument=undefined` from frontent to now cause a problem.

So, do we want to change frontend? Perhaps.

But we should even more consider if this parameter is necessary with `download_products`. It should not be, since all necessary information is passed: session and jobid.
Token should be also passed and verified by the way.

So I'd first of all **change the dispatcher** and then maybe frontend, it's not relevant.

Well, looks it's a combination of two problems and loose checking.

**Comment by burnout87** [comment]
I am trying to replicate the `instrument=undefined` behavior form the frontend, but I cannot. `instrument` seems to be always assigned. What am I missing?

**Comment by volodymyrss** [comment]
Although I am going to make a partially informed guess and suggest that you are not downloading spectra, but images.

Is this what you do?  :

![image](https://user-images.githubusercontent.com/3909535/120209034-7ad51080-c22e-11eb-91c7-c3629c1cae06.png)

For spectra it is this (as pointed out by @ferrigno in [there](https://github.com/oda-hub/doc-review-guidelines/issues/27)):

![image](https://user-images.githubusercontent.com/3909535/120209342-dacbb700-c22e-11eb-8d31-2b762d80e447.png)


It's the same endpoint, but the situation is a bit different since there are many downloadable spectra per single request, and they are presented differently.

**Comment by burnout87** [comment]
Thanks! You guessed correctly! Will do some testing and dig!

**Comment by volodymyrss** [comment]
> Thanks! You guessed correctly! Will do some testing and dig!
> 
> Also, I noticed that the `osa_fake` instrument is in the list of the installed instruments. This shouldn't happen right?

It should not.

**Comment by dsavchenko** [comment]
This does not work for me with public request. The calculated job_id seems to be wrong

**Comment by volodymyrss** [comment]
Also in UNIGE? Any request?

We have a test normally, is it not working?

**Comment by dsavchenko** [comment]
> Also in UNIGE

You still did not open the OAuth authorization for me on frontend. So I can't try there

**Comment by volodymyrss** [comment]
I confirm it does not work. Reason unclear. More information coming from recent PR will be helpful. We investigate.

**Comment by volodymyrss** [comment]
We did not really check it with frontend yet since token is not passed anyway yet, so it just does not work. But it should work for public.

**Comment by burnout87** [comment]
> We did not really check it with frontend yet since token is not passed anyway yet, so it just does not work. But it should work for public.

It really should, I am also investigating

**Comment by burnout87** [comment]
Did some more tests both from frontend and via some scripts, and still does return `403`. 
But it does locally.

**Comment by dsavchenko** [comment]
As I realised (at least for spi_acs and Antares), the cause here is that in addition to the actual parameters passed upon request, the *analysis_parameters.json* contains `"user_catalog_file": null`
job_id for analysis request is calculated from parameters passed in request, whereas for download - with parameters from this file
I haven't yet traced where this empty parameter is appended

**Comment by dsavchenko** [comment]
Got it!
https://github.com/oda-hub/dispatcher-app/pull/171

**Comment by burnout87** [comment]
> As I realised (at least for spi_acs and Antares), the cause here is that in addition to the actual parameters passed upon request, the _analysis_parameters.json_ contains `"user_catalog_file": null`
> job_id for analysis request is calculated from parameters passed in request, whereas for download - with parameters from this file
> I haven't yet traced where this empty parameter is appended

Thanks! For sure this is important to fix.
We encountered a very similar issue (`"user_catalog_file": null`) when generating the api code within the `oda_api`.

So a similar check was needed also in this case

**Comment by burnout87** [comment]
Perhaps we could also check, while generating the `job_id`, for `null` values, as well as when creating the `analysis_parameters.json`.

**Comment by dsavchenko** [comment]
Now we may close
