### ISSUE TITLE
why token is not emailed?

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/dispatcher-app#149]
In the email I see:

 "token": "",

I would find much more handy for the user to have the token available.

**Comment by volodymyrss** [comment]
You mean, for API? In frontend it will be substituted.
In API, it is quite likely to expire, it lives one day.
We could send it with a notice when it will expire.

**Comment by ferrigno** [comment]
Yes, I mean in the API code that is emailed to the user. I might want to use that query in a notebook, as suggested and having the token would be extremely handy. 

A note on the token that expires is useful. You could point to the API instruction to get a new one.

**Comment by volodymyrss** [comment]
token can be sent unlike password since it is short-lived. One of the advantages of the token.

Closed with #151
