### ISSUE TITLE
products_url should not contain `user_catalog_file=None`

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#152]
`user_catalog_file=None` in products_url seems to cause issues for frontend.

**Comment by burnout87** [comment]
Currently when generating the `products_url` is generated considering the whole dict of input parameters, but no check on the value is actually performed. Similarly to how we check in the `oda_api` for the api_code, we could also check for this url generation.

**Comment by volodymyrss** [comment]
Indeed! Could you do it or should I?

**Comment by burnout87** [comment]
I ll do it! I already know what to change
