### ISSUE TITLE
Please remove the Multi-product from light curve

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/dispatcher-app#165]
It has the very same functionality of the "share" button. So it should be removed.

I consider this important for the web page usability.

If something else is needed at the place, please put the download as for the spectrum.

**Comment by volodymyrss** [comment]
TBD if it's currently the same.

**Comment by burnout87** [comment]
I checked and the `multi-product` column is no longer there.

We can close this.

**Comment by volodymyrss** [comment]
was before:

![image](https://user-images.githubusercontent.com/3909535/125794419-08eb5e97-5800-4cff-be0b-c4f07123d654.png)

now is:

![image](https://user-images.githubusercontent.com/3909535/125794433-b00f8d4b-2c87-400b-842b-40becf0cbdcd.png)


I am kind of curious which commit, for tracking, but it's minor/

**Comment by burnout87** [comment]
This commit, in the frontend, actually, did it:

[https://github.com/oda-hub/frontend-astrooda/commit/0adb4a45b9c6382857a6ba4cc5239c02d07f5671#diff-2b927d9e179338792e53d2a0043b40fc114f70267d8812d1b9148c9faf91b85d](https://github.com/oda-hub/frontend-astrooda/commit/0adb4a45b9c6382857a6ba4cc5239c02d07f5671#diff-2b927d9e179338792e53d2a0043b40fc114f70267d8812d1b9148c9faf91b85d)
