### ISSUE TITLE
spectrum fit  returns `signature expired`

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#178]

**Comment by volodymyrss** [comment]
@ferrigno  please confirm that it is working, seems ok for me

**Comment by ferrigno** [comment]
For ISGRI, it works.
Unable to test it for JEM-X as this request is stuck

https://frontend.staging.odahub.io/cdci/astrooda//dispatch-data/resolve-job-url?job_id=71debe188416c9e4&session_id=I0KRF3VW9GJ7BF6U&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IkNhcmxvLkZlcnJpZ25vQHVuaWdlLmNoIiwibmFtZSI6ImNmZXJyaWdubyIsInJvbGVzIjoiYXV0aGVudGljYXRlZCB1c2VyLCBhZG1pbmlzdHJhdG9yLCBjb250ZW50IG1hbmFnZXIsIGdlbmVyYWwsIGludGVncmFsLXByaXZhdGUtcWxhLCBtYWdpYywgdW5pZ2UtaHBjLWZ1bGwsIHB1YmxpYy1wb29sLWhwYywgYW50YXJlcywgc2RzcyIsImV4cCI6MTYyNDAxMDc2MX0.PaxB4Gz4BWbyviibo6ng2EpSJvrFGHHmuc7IHxxKMwM

**Comment by ferrigno** [comment]
https://frontend.staging.odahub.io/cdci/astrooda/?DEC=-24.745833&E1_keV=3&E2_keV=20&RA=263.007917&T1=2020-02-15&T2=2020-02-20&T_format=isot&catalog_selected_objects=1%2C2%2C3%2C4&detection_threshold=5&instrument=jemx&integral_data_rights=public&jemx_num=1&max_pointings=5&osa_version=OSA11.0&product_type=jemx_spectrum&query_status=new&query_type=Real&radius=4&selected_catalog=%7B%22cat_column_descr%22%3A%5B%5B%22meta_ID%22%2C%22%3Ci8%22%5D%2C%5B%22src_names%22%2C%22%3CU11%22%5D%2C%5B%22significance%22%2C%22%3Ef4%22%5D%2C%5B%22ra%22%2C%22%3Ef4%22%5D%2C%5B%22dec%22%2C%22%3Ef4%22%5D%2C%5B%22FLAG%22%2C%22%3Ci8%22%5D%2C%5B%22ERR_RAD%22%2C%22%3Cf8%22%5D%5D%2C%22cat_column_list%22%3A%5B%5B1%2C2%2C3%2C4%5D%2C%5B%221A+1742-294%22%2C%22GX+1%2B4%22%2C%22GX+3%2B1%22%2C%22GX+5-1%22%5D%2C%5B21.445112228393555%2C18.095916748046875%2C91.76065826416016%2C83.3478775024414%5D%2C%5B266.5142517089844%2C263.0047912597656%2C266.97796630859375%2C270.2806701660156%5D%2C%5B-29.5125789642334%2C-24.742355346679688%2C-26.562868118286133%2C-25.07419776916504%5D%2C%5B0%2C0%2C0%2C0%5D%2C%5B0.05000000074505806%2C0.05000000074505806%2C0.05000000074505806%2C0.05000000074505806%5D%5D%2C%22cat_column_names%22%3A%5B%22meta_ID%22%2C%22src_names%22%2C%22significance%22%2C%22ra%22%2C%22dec%22%2C%22FLAG%22%2C%22ERR_RAD%22%5D%2C%22cat_coord_units%22%3A%22deg%22%2C%22cat_frame%22%3A%22fk5%22%2C%22cat_lat_name%22%3A%22dec%22%2C%22cat_lon_name%22%3A%22ra%22%7D&src_name=GX+1%2B4&use_scws=no

It work on JEM-X using the above link

**Comment by volodymyrss** [comment]
> For ISGRI, it works.
> Unable to test it for JEM-X as this request is stuck
> 
> https://frontend.staging.odahub.io/cdci/astrooda//dispatch-data/resolve-job-url?job_id=71debe188416c9e4&session_id=I0KRF3VW9GJ7BF6U&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IkNhcmxvLkZlcnJpZ25vQHVuaWdlLmNoIiwibmFtZSI6ImNmZXJyaWdubyIsInJvbGVzIjoiYXV0aGVudGljYXRlZCB1c2VyLCBhZG1pbmlzdHJhdG9yLCBjb250ZW50IG1hbmFnZXIsIGdlbmVyYWwsIGludGVncmFsLXByaXZhdGUtcWxhLCBtYWdpYywgdW5pZ2UtaHBjLWZ1bGwsIHB1YmxpYy1wb29sLWhwYywgYW50YXJlcywgc2RzcyIsImV4cCI6MTYyNDAxMDc2MX0.PaxB4Gz4BWbyviibo6ng2EpSJvrFGHHmuc7IHxxKMwM

that one causes segfault, OSA 11.1-16-g88c002b7-20210507-170349-refcat-43.0-heasoft-6.28-python-3.8.2

I leave it there https://github.com/volodymyrss/dda-ddjemx/issues/6

**Comment by volodymyrss** [comment]
> > For ISGRI, it works.
> > Unable to test it for JEM-X as this request is stuck
> > https://frontend.staging.odahub.io/cdci/astrooda//dispatch-data/resolve-job-url?job_id=71debe188416c9e4&session_id=I0KRF3VW9GJ7BF6U&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IkNhcmxvLkZlcnJpZ25vQHVuaWdlLmNoIiwibmFtZSI6ImNmZXJyaWdubyIsInJvbGVzIjoiYXV0aGVudGljYXRlZCB1c2VyLCBhZG1pbmlzdHJhdG9yLCBjb250ZW50IG1hbmFnZXIsIGdlbmVyYWwsIGludGVncmFsLXByaXZhdGUtcWxhLCBtYWdpYywgdW5pZ2UtaHBjLWZ1bGwsIHB1YmxpYy1wb29sLWhwYywgYW50YXJlcywgc2RzcyIsImV4cCI6MTYyNDAxMDc2MX0.PaxB4Gz4BWbyviibo6ng2EpSJvrFGHHmuc7IHxxKMwM
> 
> that one causes segfault, OSA 11.1-16-g88c002b7-20210507-170349-refcat-43.0-heasoft-6.28-python-3.8.2
> 
> I leave it there [volodymyrss/dda-ddjemx#6](https://github.com/volodymyrss/dda-ddjemx/issues/6)

it completed with older j_ima_iros 4.0.13

**Comment by burnout87** [comment]
So, it works also for ISGRI? I also could verify for JEM-X.

**Comment by ferrigno** [comment]
It works for both, as far as I could check
