### ISSUE TITLE
issue with CI in https://github.com/oda-hub/dispatcher-app/pull/17

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#18]

**Comment by volodymyrss** [comment]
I think it is failing because "isgri" plugin is not installed. I can reproduce it locally in env without the OSA plugin installed.
Maybe we can pytest.mark.somthing the tests which need extra plugins, or something like that.

**Comment by burnout87** [comment]
Ah True! I wasn't considering that! I will see if there is some configuration we can apply

**Comment by burnout87** [comment]
By marking the test as _dda_ pytest mark (@pytest.mark.dda), this is not executed. But Iam not entirely sure the flow that takes place when this is used

**Comment by volodymyrss** [comment]
I think it's the right approach, one of the possible ones anyway. 
But would be more natural to mark it as "isgri_plugin", adding it to https://github.com/oda-hub/dispatcher-app/blob/master/pytest.ini
