### ISSUE TITLE
seems like the token roles are not as expected (and shown) for @ferrigno

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#182]

**Comment by volodymyrss** [comment]
to check, please decode your token as so:

```python
base64.b64decode(token.split(".")[0] + "=")
```

**Comment by ferrigno** [comment]
I used the dev version of the site for the token, last time (by mistake) this might be the reason.

**Comment by volodymyrss** [comment]
I can not say for sure, but it very well might be. 
At least one of the two options would help:
* decode your token you and confirm
* try with staging

**Comment by ferrigno** [comment]
Both http://cdcidev.mtmco.net/cdci/astrooda/help/astrooda
and in

https://frontend.staging.odahub.io/cdci/astrooda/

I get

base64.b64decode(token.split(".")[0] + "=")
b'{"typ":"JWT","alg":"HS256"}'

**Comment by volodymyrss** [comment]
I meant `base64.b64decode(token.split(".")[1] + "=")` sorry

**Comment by ferrigno** [comment]
In Front end
https://frontend.staging.odahub.io/cdci/astrooda/
I get for a list of 137 scw this message
2021.06.22T17:10:36 error 400, Bad Request, scws are limited to 50

**Comment by ferrigno** [comment]
In 
http://cdcidev.mtmco.net/cdci/astrooda/help/astrooda
b'{"sub":"Carlo.Ferrigno@unige.ch","email":"Carlo.Ferrigno@unige.ch","name":"cferrigno","roles":"authenticated user, content manager","exp":1624378038}'


https://frontend.staging.odahub.io/cdci/astrooda/
b'{"email":"Carlo.Ferrigno@unige.ch","name":"cferrigno","roles":"authenticated user, administrator, content manager, general, integral-private-qla, magic, unige-hpc-full, public-pool-hpc, antares, sdss","exp":1624460375}'

**Comment by volodymyrss** [comment]
> In Front end
> https://frontend.staging.odahub.io/cdci/astrooda/
> I get for a list of 137 scw this message
> 2021.06.22T17:10:36 error 400, Bad Request, scws are limited to 50

problem here is that it frontend does not explain the cause in the same detail, even if the response is actually sent. You can inspect it in browser debug, or use this same token with API.

**Comment by volodymyrss** [comment]
> In
> http://cdcidev.mtmco.net/cdci/astrooda/help/astrooda
> b'{"sub":"[Carlo.Ferrigno@unige.ch](mailto:Carlo.Ferrigno@unige.ch)","email":"[Carlo.Ferrigno@unige.ch](mailto:Carlo.Ferrigno@unige.ch)","name":"cferrigno","roles":"authenticated user, content manager","exp":1624378038}'
> 
> https://frontend.staging.odahub.io/cdci/astrooda/
> b'{"email":"[Carlo.Ferrigno@unige.ch](mailto:Carlo.Ferrigno@unige.ch)","name":"cferrigno","roles":"authenticated user, administrator, content manager, general, integral-private-qla, magic, unige-hpc-full, public-pool-hpc, antares, sdss","exp":1624460375}'

this would definitely explain it

**Comment by burnout87** [comment]
I just tried a request from 
[https://frontend.staging.odahub.io/cdci/astrooda/](https://frontend.staging.odahub.io/cdci/astrooda/)

with 137 Scw, and it went through

**Comment by ferrigno** [comment]
It looks like roles are not implemented. Some of these data might be private, but on 

https://frontend.staging.odahub.io/cdci/astrooda/

I get a forbidden thing

001	206400530010.001
002	206500140010.001
003	206500220010.001
004	206500230010.001
005	206500240010.001
006	206500250010.001
007	206500260010.001
008	206500300010.001
009	206500310010.001
010	206500330010.001
011	206800340010.001
012	207100160010.001
013	207100170010.001
014	207100230010.001
015	207100240010.001
016	207100260010.001
017	207100270010.001
018	207100280010.001
019	207100290010.001
020	207100320010.001
021	207100330010.001
022	207100340010.001
023	207100350010.001
024	207700110010.001
025	207700120010.001
026	207700130010.001
027	207700140010.001
028	207700150010.001
029	207700160010.001
030	207700200010.001
031	207700210010.001
032	207700220010.001
033	207700230010.001
034	207700240010.001
035	207700250010.001
036	207700260010.001
037	207700270010.001
038	207700310010.001
039	207700320010.001
040	207700330010.001
041	208100470010.001
042	208100550010.001
043	208100560010.001
044	208100570010.001
045	208100580010.001
046	208100590010.001
047	208100630010.001
048	208100640010.001
049	208100650010.001
050	208100660010.001
2021.06.22T17:14:56 error 403, Forbidden, undefined

**Comment by volodymyrss** [comment]
> Did you try with a ScWs list file?

this should not make any difference

**Comment by ferrigno** [comment]
YEs, I tried with a scw list file, but it is not linked to private data, as they are all public.
I tried with other, earlier scw and got this errror (from the debug console)

exit_status: {comment: "", debug_message: "The provided job_id=3fcb883657eaf2f6 does not matc…l; parameters are derived from recorded job state", error_message: "", job_status: "failed", message: "Request not authorized", …}
job_monitor:
job_id: "3fcb883657eaf2f6"
session_id: "BP3EIY0LW79Y98DJ"
status: "failed"
__proto__: Object
job_status: "failed"
products: {}
query_status: "failed"
session_id: "BP3EIY0LW79Y98DJ"
status_code: 403
time_request: 1624375230.2438076

**Comment by volodymyrss** [comment]
> It looks like roles are not implemented. Some of these data might be private, but on
> 
> https://frontend.staging.odahub.io/cdci/astrooda/
> 
> I get a forbidden thing
> 
> 001 206400530010.001
...
> 050 208100660010.001
> 2021.06.22T17:14:56 error 403, Forbidden, undefined

I actually just saw an email with this request?

**Comment by ferrigno** [comment]
[scw_50_old_oao.txt](https://github.com/oda-hub/dispatcher-app/files/6695570/scw_50_old_oao.txt)
This is the list. ISGRI  image in 30-50 keV

**Comment by ferrigno** [comment]
> > It looks like roles are not implemented. Some of these data might be private, but on
> > https://frontend.staging.odahub.io/cdci/astrooda/
> > I get a forbidden thing
> > 001 206400530010.001
> > ...
> > 050 208100660010.001
> > 2021.06.22T17:14:56 error 403, Forbidden, undefined
> 
> I actually just saw an email with this request?

Right, I have also received it but did not notice it in time

**Comment by volodymyrss** [comment]
> [scw_50_old_oao.txt](https://github.com/oda-hub/dispatcher-app/files/6695570/scw_50_old_oao.txt)
> This is the list. ISGRI image in 30-50 keV

this is not relevant

> debug_message

the cause is in the debug message, and it is clear it is not realted to roles. It truncated though.

**Comment by ferrigno** [comment]
But why an email for my first request and not for the second one?

**Comment by burnout87** [comment]
I just managed to reproduce it, and this is the `debug_message`:

```
debug_message | "The  provided job_id=c97e09779a10af6b does not match with the  job_id=058711796b1a47bb derived from the request parameters for your  user account email; parameters are derived from recorded job state"
-- | --
```

**Comment by volodymyrss** [comment]
> But why an email for my first request and not for the second one?

which is the second one?

**Comment by volodymyrss** [comment]
I think this is a different issue entirely, the original issue was because @ferrigno  took token from dev instance, it seems clear.

**Comment by volodymyrss** [comment]
the issue is that first job_id is computed with this parameter `'use_scws': 'user_file'` while after it's converted to `scw_list:[...`. So it's because of the special case of file passing. Our test should include this case, @burnout87 . I make a separate issue.

This issue here diverted off-track - the roles of @ferrigno  are correctly implemented once correct token is used.

**Comment by volodymyrss** [comment]
I made #185 .
Meanwhile, can @ferrigno  please confirm that without passing file all works correctly with good token?

**Comment by ferrigno** [comment]
I have sent a request with 60 scw and it seems to go through both the web interface and the API. So this should be possibly solved on https://frontend.staging.odahub.io/cdci/astrooda/ 
(by making some confusion, I managed to find another bug, the power of an entropy generator ;) )
