### ISSUE TITLE
sort out `use_scws` parameter

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#186]
https://github.com/oda-hub/doc-review-guidelines/issues/49

it is explicitly ignored by oda_api:

https://github.com/oda-hub/oda_api/blob/master/oda_api/api.py#L888

which causes different (but with the same output) request being formulated from API

so it either join not be considered as parameter for job_id, or better it should be dropped at start of `run_analysis`

**Comment by burnout87** [comment]
I would say to just add it to the list of keys not to be considered for the calculation of the `job_id`.

Also, by taking a deeper look to the dispatcher's code, it really looks like such parameter is never used.

**Comment by burnout87** [comment]
> it is explicitly ignored by oda_api:
> 
> https://github.com/oda-hub/oda_api/blob/master/oda_api/api.py#L888

Here `use_scws` is ignored for the generation of the output api_code. Is there another point where this parameter is dropped before sending the request?

**Comment by volodymyrss** [comment]
I wrote what I know above. I guess it is just sent by frontend because of the way the form is, but is never used. Since input data is decided by other means (file first, then scw_list, etc). By the way, this should be clear in the oda_api doc. Else request may be confusing.

You can find that in the entire git history of dispatcher, plugin, and oda_api there are no other references to use_scws. It's not used.

Maybe we can make a test on this this scw resolution order.
