### ISSUE TITLE
could we have a simple endpoint to get updated token

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#188]
it would help a lot our isdc-critical-activity use

somethig like:

/get-token

* request.args
  * token
  * new email options

returns new token with the same exact content except for the requested email options
this would be quit simple to implement I think?

**Comment by burnout87** [comment]
It is indeed simple. Some questions:

- Is the new token generated with the same expiration date ?
- shall we extend this functionality to apply changes to the content of the token which are not only related to the email options? e.g. name, email options, roles?

**Comment by ferrigno** [comment]
The utility would be to have a token without logging it and copy from clipboard?

**Comment by volodymyrss** [comment]
> It is indeed simple. Some questions:
> 
>     * Is the new token generated with the same expiration date ?

yes, let's not give more priledges with this, only downgrade.
 
>     * shall we extend this functionality to apply changes also to the rest of the content of the token which are not only related to the emails? In theory a lot can be changed, we just have to decide what we consider modifiable at a dispatcher level e.g. name, email options, roles?

anything that could be reduced (e.g. less roles) would be useful. but let's just start with email?
we need to be sure this can not be used to escalate priviledges

**Comment by burnout87** [comment]
> anything that could be reduced (e.g. less roles) would be useful. but let's just start with email?
> we need to be sure this can not be used to escalate priviledges

Indeed! That is why I was asking since everything can be modified
