### ISSUE TITLE
implement filtering of requests

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#19]
following meeting on 2021-03-15, and the description in https://github.com/oda-hub/dispatcher-app/blob/staging-1-3/interfaces.md#usage we can start implementing the scheme for role-based handling of the requests. There several flows described there, we need to clarify them for ourselves and see how to address them progressively.

**Comment by burnout87** [comment]
Here some ideas:

According to what explained [here](https://github.com/oda-hub/dispatcher-app/blob/master/plugin-interface.md), but also implemented [here](https://github.com/oda-hub/dispatcher-app/pull/29), two approaches can be followed for the user-role interaction dispatcher-plugins:

1. provide an implementation of the instrument **configuration** loading within the plugin, and a list of required query-role pairs inside the instrument configuration: these roles will be then loaded when the instrument configuration is actually loaded within the dispatcher. This can become quite tricky the moment we want to implement a more fine-grained configuration that could specify the required role for each query


2. Expand the **instrument factory** by defining an object that provides a number of pairs role-query, to pass to the instantiation of the instrument object, and to use anytime a specific query for a given instrument is performed: checking the role within the token along with the requested query will let a certain query, of a certain instrument, assessed if it can be performed for a user (a similar object already exists: [example](https://github.com/oda-hub/dispatcher-plugin-integral/blob/fe2ccb7279b90d0c378a5e359919931cc873a5bf/cdci_osa_plugin/osa_isgri.py#L89)). However, here we would have to change and expand every plugin code

**Comment by burnout87** [comment]
In order to limit the possibilities directly over the interface for a certain user, the login procedure should be handled within the dispatcher in order to apply (if needed) a _restricted_ view for a user depending on its role.

Does this make any sense?

Perhaps @motame can shed some light on this point...

**Comment by volodymyrss** [comment]
>  1.    provide an implementation of the instrument configuration loading within the plugin, and a list of required query-role pairs inside the instrument configuration: these roles will be then loaded when the instrument configuration is actually loaded within the dispatcher. This can become quite tricky the moment we want to implement a more fine-grained configuration that could specify the required role for each query

I think it is rarely necessary or to have fine-grained control by query but not detailed control by query parameters.

So I would reduce this option to a single config setting: the roles required by any queries in this plugin. Perhaps we should assume by default that all roles listed need to be satisfied.
It may be a universally required option. For full-public plugins the value will be empty list of required roles.

This way, older plugins may be loaded without change.

>  2.   Expand the instrument factory by defining an object that provides a number of pairs role-query, to pass to the instantiation of the instrument object, and to use anytime a specific query for a given instrument is performed: checking the role within the token along with the requested query will let a certain query, of a certain instrument, assessed if it can be performed for a user (a similar object already exists: example). However, here we would have to change and expand every plugin code

We can add a method in parent query class, in dispatcher, checking if the query allows request with collection of roles written in the token. In the parent dispatcher class this method would return True by default.

This way, by default, all plugins will be still valid.

> In order to limit the possibilities directly over the interface for a certain user, the login procedure should be handled within the dispatcher in order to apply (if needed) a _restricted_ view for a user depending on its role.

I think frontend can implement hiding of some parts by it's own means, as @motame explained to us.
Hidden parts may or may not be instrument panels, which is nice.
This was previously discussed and noted briefly on top of the [doc section](https://github.com/oda-hub/dispatcher-app/blob/staging-1-3/interfaces.md#usage).

But since dispatcher has to be accessed without frontend too, so it needs to implement filtering as well.
Hence filtering has to be somehow in two places.
But I think this is not really duplication since it's a bit of a different thing. And it is necessary to define roles in dispatcher and coordinate them with that in front-end.
It may lead to cases when frontend shows something and dispatcher refuses, but it's not too big of a deal, one can be a bit careful.


> 
> Does this make any sense?
> 
> Perhaps @motame can shed some light on this point...

**Comment by burnout87** [comment]
> > 2. Expand the instrument factory by defining an object that provides a number of pairs role-query, to pass to the instantiation of the instrument object, and to use anytime a specific query for a given instrument is performed: checking the role within the token along with the requested query will let a certain query, of a certain instrument, assessed if it can be performed for a user (a similar object already exists: example). However, here we would have to change and expand every plugin code
> 
> We can add a method in parent query class, in dispatcher, checking if the query allows request with collection of roles written in the token. In the parent dispatcher class this method would return True by default.
> 
> This way, by default, all plugins will be still valid.
> 
I really like this approach, quite easy to implement and to expand in future development. It anyway implies the extension of the current plugins with this functionality. Or did I misunderstand your comment?

**Comment by volodymyrss** [comment]
> > This way, by default, all plugins will be still valid.
> 
> I really like this approach, quite easy to implement and to expand in future development. It anyway implies the extension of the current plugins with this functionality. Or did I misunderstand your comment?

It will imply extension of some of the plugins, but only those that will require restrictions. 
Or I misunderstand which functionality you mean?

**Comment by burnout87** [comment]
> > > This way, by default, all plugins will be still valid.
> > 
> > 
> > I really like this approach, quite easy to implement and to expand in future development. It anyway implies the extension of the current plugins with this functionality. Or did I misunderstand your comment?
> 
> It will imply extension of some of the plugins, but only those that will require restrictions.
> Or I misunderstand which functionality you mean?

Exactly my point, some plugins will have to be extended, but only those we need to. Plus, we can apply the rules we want at anytime in the future

**Comment by burnout87** [comment]
With [29f5928d02e01cb4fcc4e52a389169b22a3a05ab](https://github.com/oda-hub/dispatcher-app/commit/29f5928d02e01cb4fcc4e52a389169b22a3a05ab) a first implemenbtaiton of this approach has been attempted.

In particular, the instrument [_empty_ ](https://github.com/oda-hub/dispatcher-app/blob/role-based-queries/cdci_data_analysis/plugins/dummy_instrument/empty_instrument.py) a simple rule is applied for the only query it provides ([here](https://github.com/oda-hub/dispatcher-app/blob/role-based-queries/cdci_data_analysis/plugins/dummy_instrument/data_server_dispatcher.py)). The role _general_ needs to be present in the token in order to be authorized to perform the query.

Then, before actually executing the query, permissions for the query execution are assessed against the user roles.

**Comment by volodymyrss** [comment]
looks good!
Start a PR?

we could restrict magic with magic role. Not sure if it will be always necessary, but I guess so.

for integral - for all queries, we can do the following:

```python
if use_max_pointings > 50 or scw_list.split(",") > 50:
    return 'unige-hpc-full' in roles:

return True   
```

where use_max_pointings and  scw_list are query parameters and 'unige-hpc-full' is a role according to [doc](https://github.com/oda-hub/doc-multi-user/blob/main/plan-roles-users.md)

There is another mechanism needed there, but I will rather implement it directly in the function once placeholder is ready.

**Comment by burnout87** [comment]
Cool! I will try to implement it then...and test!

**Comment by burnout87** [comment]
Merge complete! 
To mention during the next meeting on Monday:

- queries now support the check of user roles against the input param
- two simple test queries for the _empty_ parameter have been provided: one is public and has "restricted" access
- TBD decide on which roles for which queries/instrument we want to provide

**Comment by volodymyrss** [comment]
Ok! I have inserted it right [there](https://github.com/oda-hub/meetings/blob/main/2021-03-29/agenda.md)
