### ISSUE TITLE
add an instruction for user in case of expire token

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#192]
if frontend, suggest to reload/relogin
if api - generate new token

**Comment by burnout87** [comment]
We could provide an end-point to be used to evaluate the status of the token by returning a number of information, this can be:

- expired/not-expired
- available roles
- ...

**Comment by volodymyrss** [comment]
> We could provide an end-point to be used to evaluate the status of the token by returning a number of information, this can be:
> 
>     * expired/not-expired
> 
>     * available roles
> 
>     * ...

maybe. But for now, we could just modify the error message.
