### ISSUE TITLE
send email upon completion of long requests

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#20]
token contains email. If request took a while - and email can be useful. There could be other factors to control email delivery. TBD

**Comment by burnout87** [comment]
Which email address should be used?

Is there already something like info-at-astro etc etc ?

**Comment by volodymyrss** [comment]
the email needs to be sent to the user - i.e. the one found in the token.

**Comment by volodymyrss** [comment]
but it's a good idea to send one to us too. We have an email, like astroooda-feedback, we should ask @motame , I forgot.
we can also send a backup one to team@odahub.io

**Comment by burnout87** [comment]
Sorry, I didn't specify, which email should be used as a sender? That's why I gave the example wit info at ...

**Comment by volodymyrss** [comment]
yes, well, we still should send it to info@astro smth. for backup. 
as for the from, you can as well use team@odahub.io . It will work now for reply, and it includes you. And we see if we find some alternative.

**Comment by volodymyrss** [comment]
oh, "from", "reply-to" emails as well as SMTP details should be configurable. They depend on the deployment. For experiment, you can even use localhost. Or gmail. For pytest - maybe [this](https://pypi.org/project/pytest-localserver/)?

**Comment by burnout87** [comment]
Yes, those should be configurable, depending on the deployment, like we did for the secret key

Will look into it, I also found [this](https://realpython.com/python-send-email/).

**Comment by burnout87** [comment]
Something there was no time to discuss during the last meeting: how can we define a "long" request?
I thought of two possible scenarios:

- Execution time exceeds a certain threshold
- Asynchs requests

Any other situation to take into account?

**Comment by ferrigno** [comment]
I think that every request should be considered as long, UNLESS products are ready and can be directly retrieved at the first call. I do not know exactly if this is equivalent to asynchronous request, you should check in the dispatcher, I believe.

**Comment by volodymyrss** [comment]
> Something there was no time to discuss during the last meeting: how can we define a "long" request?
> I thought of two possible scenarios:
> 
>     * Execution time exceeds a certain threshold

Yes. Maybe we can store this user choice in token.
By the way, note that this will probably only happen during "callback" requests, i.e. when user is not active.

> 
>     * Asynchs requests

This should only apply to async request, since sync ones can never be long really - they will timeout.

> 
> 
> Any other situation to take into account?

**Comment by volodymyrss** [comment]
> I think that every request should be considered as long, UNLESS products are ready and can be directly retrieved at the first call. I do not know exactly if this is equivalent to asynchronous request, you should check in the dispatcher, I believe.

this more or less means asynchronous.

but short asynch requests should not necessarily trigger email, not for all users anyway. We can make threshold parameter.

Oh, by the way, any failed request should be sent to the user with a kind message saying that we are working on it.
And also sent to us. Though we will notice anyway, it's good to have a copy.
In fact, at first, we might consider sending us all messages CC.

**Comment by ferrigno** [comment]
Yes, CC to a service address is fundamental !

**Comment by volodymyrss** [comment]
> Yes, CC to a service address is fundamental !

you know not how much you will get. Years ago, I had mattermost notifcations for every requests, and eventually switched them off. It's worse now.
Also, we should be a bit conscious about not spying on users. 
They are recorded internally of course.

Oh, and another element: users might want to get email even on sending a request, with a request URL (this URL should be included in all relevant emails). 
This will allow them to come back to the request.

**Comment by burnout87** [comment]
https://github.com/oda-hub/dispatcher-app/pull/56

**Comment by burnout87** [comment]
I am struggling in understanding the difference between the two async settings:

- one is set directly on the instrument
[https://github.com/oda-hub/dispatcher-app/blob/6330adeb99832ec23d05943e705badb87badd10a/cdci_data_analysis/flask_app/dispatcher_query.py#L1014-L1018](https://github.com/oda-hub/dispatcher-app/blob/6330adeb99832ec23d05943e705badb87badd10a/cdci_data_analysis/flask_app/dispatcher_query.py#L1014-L1018)
- the other one is for the whole dispatcher
[https://github.com/oda-hub/dispatcher-app/blob/6330adeb99832ec23d05943e705badb87badd10a/cdci_data_analysis/flask_app/dispatcher_query.py#L100-L104](https://github.com/oda-hub/dispatcher-app/blob/6330adeb99832ec23d05943e705badb87badd10a/cdci_data_analysis/flask_app/dispatcher_query.py#L100-L104)

**Comment by volodymyrss** [comment]
Those two are entirely different. I understand the confusion.
Asynchronous request handling is a fairly general concept, you understand, and it happens to happen in several places here. 

The are called differently here, one `run_asynch` has to do with asynchronous interaction between dispatcher and backend: job monitor, etc.  Another, `async_dispatcher` - between dispatcher and dispatcher client (oda_api or frontend)

`run_asynch` functionality is fairly complex and uses custom job management. But it is also most important and non-trivial.

`async_dispatcher` simply queues requests to dispatcher in celery, making sure dispatcher always returns request immediately unless the response is already ready.
It is a lot more simple, and you can disable it (with DISPATCHER_ASYNC_ENABLED=no). Then, it can be debugged and re-enabled quite simply, since if dispatcher is responding correctly when DISPATCHER_ASYNC_ENABLED=no, the same responses will be cached and pre-processed with  DISPATCHER_ASYNC_ENABLED=yes.
`async_dispatcher` functionality is concentrated in limited parts of code, so if you do not modify those, all will be ok.

So I suggest if unsure, set  DISPATCHER_ASYNC_ENABLED=no.
And proceed to deal with run_asynch.

**Comment by burnout87** [comment]
Thanks, way more clear now.

I was trying to understand on when the request completion email should be placed, and in which cases we consider the request aynchronous.

Untile now, I have never tried to set DISPATCHER_ASYNC_ENABLED to yes, always kept  no.

**Comment by burnout87** [comment]
> Those two are entirely different. I understand the confusion.
> Asynchronous request handling is a fairly general concept, you understand, and it happens to happen in several places here.
> 
> The are called differently here, one `run_asynch` has to do with asynchronous interaction between dispatcher and backend: job monitor, etc. Another, `async_dispatcher` - between dispatcher and dispatcher client (oda_api or frontend)
> 
> `run_asynch` functionality is fairly complex and uses custom job management. But it is also most important and non-trivial.
> 
> `async_dispatcher` simply queues requests to dispatcher in celery, making sure dispatcher always returns request immediately unless the response is already ready.
> It is a lot more simple, and you can disable it (with DISPATCHER_ASYNC_ENABLED=no). Then, it can be debugged and re-enabled quite simply, since if dispatcher is responding correctly when DISPATCHER_ASYNC_ENABLED=no, the same responses will be cached and pre-processed with DISPATCHER_ASYNC_ENABLED=yes.
> `async_dispatcher` functionality is concentrated in limited parts of code, so if you do not modify those, all will be ok.
> 
> So I suggest if unsure, set DISPATCHER_ASYNC_ENABLED=no.
> And proceed to deal with run_asynch.

For having more understanding regarding the handling of a call_back within an async call, is the _callback_handle_ here configured in a way that the 'call_back' REST call gets called at the completion of a task, when run_asynch is true?

[https://github.com/oda-hub/dispatcher-app/blob/6330adeb99832ec23d05943e705badb87badd10a/cdci_data_analysis/analysis/job_manager.py#L321-L346](https://github.com/oda-hub/dispatcher-app/blob/6330adeb99832ec23d05943e705badb87badd10a/cdci_data_analysis/analysis/job_manager.py#L321-L346)

**Comment by volodymyrss** [comment]
> 
> For having more understanding regarding the handling of a call_back within an async call, is the _callback_handle_ here configured in a way that the 'call_back' REST call gets called at the completion of a task, when run_asynch is true?
> 
> https://github.com/oda-hub/dispatcher-app/blob/6330adeb99832ec23d05943e705badb87badd10a/cdci_data_analysis/analysis/job_manager.py#L321-L346

yes. To be clear, `call_back` is called by the backend to update on job progress. dispatcher stores these updates in a directory. It might return completion, in which case an email should be sent.

**Comment by burnout87** [comment]
Are these the only possible status that can be returned anytime an on the job progress is available (and then logged in the directory)?
[https://github.com/oda-hub/dispatcher-app/blob/6330adeb99832ec23d05943e705badb87badd10a/cdci_data_analysis/analysis/job_manager.py#L91-L92](https://github.com/oda-hub/dispatcher-app/blob/6330adeb99832ec23d05943e705badb87badd10a/cdci_data_analysis/analysis/job_manager.py#L91-L92)

**Comment by volodymyrss** [comment]
I do not know they are all necessary too.  Oh maybe I should make that test for async now, as we discussed? I could do it before lunch.

**Comment by burnout87** [comment]
That would help me a lot thanks. If possible, we could do it together so that I can actually see what is necessary and understand more about the flow in this specific case

**Comment by burnout87** [comment]
> Oh, and another element: users might want to get email even on sending a request, with a request URL (this URL should be included in all relevant emails).
> This will allow them to come back to the request.

Where can this be URL retrieved ?

**Comment by volodymyrss** [comment]
> > Oh, and another element: users might want to get email even on sending a request, with a request URL (this URL should be included in all relevant emails).
> > This will allow them to come back to the request.
> 
> Where can this URL be retrieved ?

you can see how it is constructed in [here](https://github.com/oda-hub/dispatcher-plugin-integral-all-sky/blob/55249983d664b5b8348ceb8f3a5d54b4b84a4d63/dispatcher_plugin_integral_all_sky/spiacs_lightcurve_query.py#L312-L315)

It uses this base URL from config and adds encoded parameters.

**Comment by burnout87** [comment]
thanks! Just realized I actually already asked the very same question a few days ago...

**Comment by burnout87** [comment]
Completed with #56
