### ISSUE TITLE
url in email api code

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#205]
disp = DispatcherAPI(url="https://www.astro.unige.ch/mmoda/", instrument="mock")

should become

disp = DispatcherAPI(url="https://www.astro.unige.ch/mmoda/dispatch-data", instrument="mock")

**Comment by burnout87** [comment]
We should also change the default value used by the method within the oda_api

[https://github.com/oda-hub/oda_api/blob/6e710329c2e7e25bc9bf098ca3c4306eb68dda23/oda_api/api.py#L885](https://github.com/oda-hub/oda_api/blob/6e710329c2e7e25bc9bf098ca3c4306eb68dda23/oda_api/api.py#L885)
