### ISSUE TITLE
RuntimeError('spectral fit failed, Xspec Error: Error executing command: fit')

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#208]
experienced this: RuntimeError('spectral fit failed, Xspec Error: Error executing command: fit')

should make sure it gives meaningful exception

**Comment by burnout87** [comment]
Does it come from the backend ?

**Comment by volodymyrss** [comment]
no, it comes from the dispatcher, which is why I created it in the dispatcher.

**Comment by burnout87** [comment]
Ok, if you provide some information regarding the test you were running when you got this error, I will try to reproduce it once I am back.

**Comment by volodymyrss** [comment]
it's going to fail sometimes. Dispatcher should detect any errors and respond meaningfully. It's hard to reproduce, but it might be possible to invent a case.

**Comment by volodymyrss** [comment]
actually maybe this message is ok
