### ISSUE TITLE
wrong URL in "API code"? 

### ISSUE THREAD

**Issue by andriineronov** [oda-hub/dispatcher-app#209]
I've noticed that if I click on "API code" button, the URL is "'https://www.astro.unige.ch/mmoda/", and it does not work.... If I add "'https://www.astro.unige.ch/mmoda/dispatch-data", the API works. Should this be corrected?

**Comment by volodymyrss** [comment]
it's actually a dispatcher thing. It's a very small change, missed since it was not easily testable. #210 
I deployed it now in production, but will complete the test tomorrow.

**Comment by volodymyrss** [comment]
![image](https://user-images.githubusercontent.com/3909535/127043551-51e3d845-fec5-43a9-8d46-2ff012ac6ab7.png)

Please check, @andriineronov , and if it's unassign self. We will then proceed to finish tests and so.

**Comment by andriineronov** [comment]
Ok it works now
