### ISSUE TITLE
oda_api returns InstrumentQueryBackEnd' object has no attribute 'instrument' 

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#21]
CF experiences in some cases, not clearly different from other, the following response:

```
RuntimeError: ('request json does not contain query_status: %s', .......)
```
where .... is a long json response:

```json
{
 "cdci_data_analysis_version": "1.3.0",
 "config": {
 "dispatcher-config": {
 "cfg_dict": {
 "dispatcher": {
 "dispatcher_port": 8000,
 "dispatcher_service_url": "http://oda-dispatcher:8000",
 "dispatcher_url": "0.0.0.0",
 "products_url": "http://www.astro.unige.ch/cdci/astrooda_"
 }
 },
 "origin": {
 "filepath": "/dispatcher/conf/conf_env.yml",
 "set_by": "command line /cdci_data_analysis/bin/run_osa_cdci_server.py:__main__"
 }
 },
 "plugins": {
 "cdci_magic_plugin": {
 "config_file": "/dispatcher/conf/conf.d/magic_data_server_conf.yml"
 },
 "cdci_osa_plugin": {
 "config_file": "/dispatcher/conf/conf.d/osa_data_server_conf.yml"
 },
 "cdci_spiacs_plugin": {
 "config_file": "/usr/local/lib/python3.8/site-packages/cdci_spiacs_plugin/config_dir/data_server_conf.yml"
 }
 }
 },
 "debug_mode": "yes",
 "error_message": "'InstrumentQueryBackEnd' object has no attribute 'instrument'",
 "installed_instruments": [
 "magic",
 "isgri",
 "jemx",
 "osa_fake",
 "spi_acs"
 ],
 "message": "request not valid",
 "oda_api_version": "1.1.5"
}
```

we should test it with master branch oda_api, and also with recently merged/deployed https://github.com/oda-hub/dispatcher-app/pull/17

**Comment by volodymyrss** [comment]
internal tracking was [there](https://redmine.astro.unige.ch/issues/23891), moved on to this issue here since scope is clear.

**Comment by ferrigno** [comment]
The very same query does NOT cause an error on staging-1.2

**Comment by volodymyrss** [comment]
> The very same query does NOT cause an error on staging-1.2

good to know. 
this is not surprising, since 1.2 is supposed to be stable. If it has issues - we address them as incidents, in a different flow.
While the interface has to be compatible, 

If you want, you can make an end-to-end test workflow, a bit like this: https://github.com/volodymyrss/oda_test_kit/blob/master/test_image.py

We could then more easily repeat it. 

You may also repeat it, since platform was redeployed since your request (as seen in the versions reported).
And also please do try to update oda_api, from pip or even better from master.

**Comment by dsavchenko** [comment]
I also experienced this in the past. The actual causes were different (as far as I remember) and were found deeper in logs

**Comment by volodymyrss** [comment]
> I also experienced this in the past. The actual causes were different (as far as I remember) and were found deeper in logs

that's quite possible. Error treatment is very redundant.

**Comment by volodymyrss** [comment]
to that end, we should at least start by making actual causes more obvious: sending to sentry, clearly indicating in the long, and providing a distilled request to the user

**Comment by volodymyrss** [comment]
I propose to close this since it actually reflects other issues especially with respect to exception handling. Please re-open if unclear.
