### ISSUE TITLE
promised "up to 500 ScWs" upon login does not work? 

### ISSUE THREAD

**Issue by andriineronov** [oda-hub/dispatcher-app#211]
I've tried to login and ask for more than 50 ScWs for ISGRI analysis, get a message 

2021.07.26T21:54:37 error 403, Forbidden, undefined 

Is this a bug? Or I need to do more?

**Comment by volodymyrss** [comment]
Your roles were not set. Once we enable the rules we set specific default roles, but the roles set now are not those we want. I changed it.

We should make the default roles different.
