### ISSUE TITLE
email not sent: another case of very long lines

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#218]
Very long string was in ScW list.

```python
"scw_list": "115000860010.001,115000870010.001,115000980010.001,115000990010.001,115001000010.001,115001010010.001,115001020010.001,115001030010.001,115001040010.001,115001050010.001,115
001060010.001,117100210010.001,118100040010.001,118100050010.001,118900100010.001,118900120010.001,118900130010.001,118900140010.001,119000020010.001,119000030010.001,119000040010.001,119000
050010.001,119000190010.001,119900370010.001,119900480010.001,119900490010.001,119900500010.001,119900510010.001,119900520010.001,119900530010.001,119900540010.001,119900550010.001,119900560
010.001,119900570010.001,119900670010.001,119900680010.001,119900690010.001,119900700010.001,119900710010.001,119900720010.001,119900730010.001,119900740010.001,119900750010.001,119900760010
.001,119900770010.001,119900880010.001,119900890010.001,119900900010.001,119900910010.
```

Line reformatting (by black) is not always working, if line is uninterrupted.

We should also note to make sentry warning if email not sent. edit: it is

**Comment by volodymyrss** [comment]
Request of @andriineronov of this morning

**Comment by burnout87** [comment]
Was this found in the email ?
Do you have some more details regarding the request that generated this ?

**Comment by volodymyrss** [comment]
> Was this found in the email ?

Well, yes.

> Do you have some more details regarding the request that generated this ?

Which further details would be helpful?

**Comment by burnout87** [comment]
> 
> Which further details would be helpful?

Ideally it would be helpful to reproduce the behavior entirely, so to debug it

**Comment by volodymyrss** [comment]
> > Which further details would be helpful?
> 
> Ideally it would be helpful to reproduce the behavior entirely, so to debug it

I strongly suspect we could reproduce it by passing long string to `scw_list`,  similar to that in the issue title.

**Comment by volodymyrss** [comment]
If you want to have a look go ahead. Else I can do it, I worked on this part. 

You can see how it fails here:

https://github.com/oda-hub/dispatcher-app/commit/452bab4984183722b77488a3f2ab71a6dc5a8b62

The problem is that guaranteed line wrapping in python code is a complex business. I relied on `black` code formatter, and it skips some cases.
I previously already added a workaround.
It can be expanded.

Maybe even more importantly, we should probably still send an email in such a case. Explaining that code could not be added. Or maybe even attach a file with code.

**Comment by volodymyrss** [comment]
So, @burnout87  are you onto it or should I? So we do not duplicate!

**Comment by burnout87** [comment]
> So, @burnout87 are you onto it or should I? So we do not duplicate!

No, I am not.

I was in another call till now
