### ISSUE TITLE
`Directory not empty` error

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#221]
This should basically never happen.

```
JEM-X1 failed with weird error
2021.08.19T15:44:25 error 410, Gone, [Errno 39] Directory not empty: 'temp_sid_11QD1SV187JKV41L'
2021.08.19T15:44:26 error 400, Bad Request, [ InstrumentQueryBackEnd : jemx ] constructor failed: [Errno 2] No such file or directory: 'temp_sid_11QD1SV187JKV41L/list.txt'
```

The root problem can be that there is no data (which is normal in this case for this request configuration, this should be adjusted otherwise)

**Comment by volodymyrss** [comment]
is it possible to understand if this can ever happen? in any case, we should make sure there is sentry error with note of  what's in the directory

**Comment by burnout87** [comment]
I am struggling to understand why it actually happened, but most certainly it did when trying to load a file with a `scw_list` loaded from the frontend.

**Comment by burnout87** [comment]
Also, if an exception is caught when loading the input files from the frontend, a sentry error is captured, with details of the failed step. Though there are no indication regarding the content of the directory. Yes, those should be included

**Comment by volodymyrss** [comment]
right, it's hard to understand. hence my suggestion to add more info in output and especially sentry!
