### ISSUE TITLE
convert T1 and T2 to ISOT **before** computing job ID

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#227]

**Comment by burnout87** [comment]
I can take care of this since it is needed for the release, is there  an example code I can inspect to understand the conversion to apply?

**Comment by volodymyrss** [comment]
if, for example, `T1=51000 ` in API, a job_id will be calculated with this value.
But, once parameter is processed, it will be converted in the same format, ISOT. And this will appear in the url. Which means that UTL will lead to another job_id.
This can be verified with a simple test.

**Comment by burnout87** [comment]
some small investigation is needed on when and how the parameters are set

**Comment by volodymyrss** [comment]
this seems like an appropriate test but inappropriate software behavior.

ok, but, if you do not set `T1`, it's set to what? To the default, right? Taken from the `Parameter` instance?

**Comment by burnout87** [comment]
> this seems like an appropriate test but inappropriate software behavior.
> 

inappropriate because the frontend would not know what to do with those values received from the URL?

**Comment by burnout87** [comment]
> 
> I guess it would, given also the parameter on time format. But let's not do this!
> 

I don't think there's a conversion applied at frontend level, that uses also the time format information yet, but I might be wrong

> Instead, we need it so that the parameter from `par_dic` is set in instance of `class Time(Parameter)`. And then the value is extracted from this instance. And it needs to be extracted in standardized format. And only this value should be used in the job_id, URL, api code. This applies to many parameters, in principle. But it's most obvious for `Time`.

Ok, I think I already have an idea on how to proceed and where to put mu hands on, "should" be not too much work. 

So, we want that the time format used for job_id, URL, api code remains consistent across them, and this is the following: 

`2017-03-06T13:26:48.000`
