### ISSUE TITLE
complete transition from separating url and port both in dataserver (plugin) and dispatcher config

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#24]
it's long to explain, and history of this can be deduced in the code, but due to some miscommunication dispatcher originally assumed port was added as a separate parameter and glued to the host name, which was also called url, which meant that url of dispatcher could never have a prefix (like it is always the case in dispatcher seen from frontend).
Anyway, if any of the above is unclear, which it likely is, we need to discuss.

But, quite simply, we need to get rid of all mention of "port", "host", "protocol" etc, and only keep url - since we really only use the urls.

An example of the issue to which it leads was here:

https://github.com/oda-hub/dispatcher-app/pull/23

**Comment by burnout87** [comment]
I think that with [29](https://github.com/oda-hub/dispatcher-app/pull/29) this is addressed/tackled.

**Comment by dsavchenko** [comment]
> I think that with [29](https://github.com/oda-hub/dispatcher-app/pull/29) this is addressed/tackled.

Yes, but only partially. 29 address this on the level of plugin/instrument configuration. There is also ConfigEnv class in the same file, where _host, _port should also be disregarded

**Comment by burnout87** [comment]
Right, perhapos  we the same approach used to refactor the _from_conf_dict_ function can be used to refactor the constructor of the class.

**Comment by burnout87** [comment]
Just noticed that also the [job_factory](https://github.com/oda-hub/dispatcher-app/blob/bc2be600665c090bd0b9172a4b2cb4b1aad48dc2/cdci_data_analysis/analysis/job_manager.py#L321) relies on the url and port, but in all its usages (eg [here](https://github.com/oda-hub/dispatcher-app/blob/bc2be600665c090bd0b9172a4b2cb4b1aad48dc2/cdci_data_analysis/flask_app/dispatcher_query.py#L1066)) the port is None and assumed that it will be included within the _dispatcher_service_url_ . So, also that should be considered I guess

**Comment by volodymyrss** [comment]
yeah part of this https://github.com/oda-hub/dispatcher-app/issues/24 . Actually as far as https://github.com/oda-hub/dispatcher-app/issues/24 concerned, I would go through all mentions of port and host and make sure they are not used and issue a warning they this will be discarded in the next major version release.

**Comment by dsavchenko** [comment]
It should be reopened as it is not completed in dispatcher config

**Comment by volodymyrss** [comment]
We should probably be extra careful with these auto-close and revise them before PR is done. Especially if seems to PR address several at once.
