### ISSUE TITLE
problem with default values

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#247]
I observe that while the correct request is sent to dispatcher, once the job is done, another request is sent, with just the default parameters. Then, default result is retrieved. This is of course very problematic. Strangely, it does not happen always - if the result is ready, it returns.

this happens just to the scw_list it seems. Other values are used correctly.

This is as much information as I can give at this time. I suggest to reproduce this behavior with oda_api test. I will try to debug it.

**Comment by volodymyrss** [comment]
The problem is that module variable `params_not_to_be_included` is not safe, as it preserves state between requests.
Any request without scw_list permanently adds `scw_list` to  `params_not_to_be_included`, and all other requests will behave as if there is no `scw_list` passed.
The impact was not easy to notice since the problem happens only after certain sequence of requests. But when it happens it's very bad for the user, as the result is returned, but its a wrong result, and it's hard to tell immediately why.

Also tests did not notice this, even if a particular request sequence is introduced, since they did not test what's passed to the backend, only the original `par_dic`. I changed this.

you can see how this request prevents any further scw requests:

https://github.com/oda-hub/dispatcher-app/blob/3e1404f681019f2cbab43100302cfd2fa849f102/tests/test_job_management.py#L1416-L1418

We should be very cautious about introducing state in this web service. It's might have unexpected impact.
So far, dispatcher keeps all reusable state in the scratch-job dir. It also builds up something during the request, but not reusing anything between the requests. We should not change this without a very good reason.

**Comment by burnout87** [comment]
I have to admit I didn't consider this scenario and as you said, it is quite hard to spot while testing.

> https://github.com/oda-hub/dispatcher-app/blob/3e1404f681019f2cbab43100302cfd2fa849f102/tests/test_job_management.py#L1416-L1418
> 

What do you mean with the setting global variable?

**Comment by volodymyrss** [comment]
> I have to admit I didn't consider this scenario and as you said, it is quite hard to spot while testing.

Sure, just to be clear, we have to be always very cautious about global, and especially mutable variables. If we accidentally have any (I hope not) they should be removed. It has to be clear as a basic principle. With this practice, we may not have to consider complex unexplained cases.

> 
> > https://github.com/oda-hub/dispatcher-app/blob/3e1404f681019f2cbab43100302cfd2fa849f102/tests/test_job_management.py#L1416-L1418
> 
> What do you mean with the setting global variable?

**Comment by burnout87** [comment]
Thanks. I could see how by using the `dispatcher_long_living_fixture` instead of the `dispatcher_live_fixture` the problem could be exposed!

**Comment by volodymyrss** [comment]
> Thanks. I could see how by using the `dispatcher_long_living_fixture` instead of the `dispatcher_live_fixture` the problem could be exposed!

`dispatcher_long_living_fixture`  does not really help. Actually, it makes the testing depend on order of tests, which is bad.
`dispatcher_long_living_fixture` should behave exactly the same as  `dispatcher_live_fixture`, since it's only made for optimization, preserving dispatcher between tests. If it does not behave the same, there is another problem with tests.

**Comment by burnout87** [comment]
I mean that what I could see is that while using the `dispatcher_long_living_fixture` is that `params_not_to_be_included` was not re-initialized to its original state (with only `UserCatalog`), thus hsving such a list never cleared up.

**Comment by volodymyrss** [comment]
The problem is that in real operations it does get cleared up. In real operations, dispatcher is not restarted for every request.

We want tests to be independent, so while `dispatcher_long_living_fixture` with several tests may trigger the problem in some of them randomly, depending on the test order, it's not good. It makes testing inconsistent. 
Ideally, each test should start fresh like with `dispatcher_live_fixture`.  But we need  `dispatcher_long_living_fixture` for performance. It works just fine if we clean directories and do not keep state in dispatcher variables.

So while  `dispatcher_long_living_fixture` does trigger the same problem as real operations, it does not allow consistent testing without special care.
So it's not really good to use `dispatcher_long_living_fixture` for testing this. It would be better to use `dispatcher_live_fixture` instead.

But, the test of the actually used scw list will properly fail in any case. Just with `dispatcher_long_living_fixture` more things will randomly and incomprehensibly fail. So at least we will know to fix. And we can start by changing to  `dispatcher_live_fixture`  to see if there is test interaction. 

So the way to properly expose and test the problem is not to use `dispatcher_long_living_fixture`, but to make sequence of requests to the same dispatcher (as I did in the sniplet above) with  `dispatcher_live_fixture` . And then, change to  `dispatcher_long_living_fixture` for performance.
