### ISSUE TITLE
Dispatcher not responding ?

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/dispatcher-app#250]
I try to get instrument and product description, but encounter an error  

oda-api-1.1.22
disp = DispatcherAPI(url="https://www.astro.unige.ch/mmoda//dispatch-data", wait=False)
![image](https://user-images.githubusercontent.com/2527219/135819263-22db3bd2-ef92-4eef-ad59-8cb40b3282e0.png)

**Comment by burnout87** [comment]
I think it is hapening with the `OSAVersion` parameter the `_units` has not been defined. Can you conferm @volodymyrss  ?

I just tried locally and go the following error:
'''
E           AttributeError: 'OSAVersion' object has no attribute '_units'
'''

**Comment by volodymyrss** [comment]
https://github.com/oda-hub/dispatcher-plugin-integral/issues/62

**Comment by volodymyrss** [comment]
there are two different issues. One is that parameter is not complete (with unnecessary information like units) - this is in the plugin. Another is how the dispatcher deals with it.
