### ISSUE TITLE
give more information with an exception

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#261]
to produce not-so-comprehensive error:

* open mmoda front page, with all default parameters
* put `Crab` in source name. Click `resolve`.
* click `submit` - to get isgri image, by default.

this will appear:

![image](https://user-images.githubusercontent.com/3909535/137542789-6c21131b-aaea-49df-abec-ac1c421598f9.png)

there is no useful result there. But we could make the message more informative. E.g., add:

```
Unfortunately, the analysis product you requested is empty, since there is no usable data for the parameter combination you requested: time period, software version, etc.
We did not find any unexplained exceptions.
This additional message may be helpful:

HERE_PUT_BACKEND_MESSAGE
```

**Comment by burnout87** [comment]
Something like that would already be better I guess. I will add the additional information

![image](https://user-images.githubusercontent.com/3757833/138255699-5fa12ce3-9a55-436b-b93f-0c00d242ad02.png)
