### ISSUE TITLE
sort out situation with invalid config crash/nocrash

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#27]
following incidental confusion caused by accidental merge, we should sort this out:

https://github.com/oda-hub/dispatcher-app/pull/23
https://github.com/oda-hub/dispatcher-app/pull/26

@dsavchenko could you please finish what you intended? Thanks! And sorry for the small mess.

**Comment by dsavchenko** [comment]
Ok. Let's finally decide what is actually the wrong config. 
Being instrument-agnostic: what keys beside the data_server_url are strictly necessary, and what are optional?

Then I have an idea. I can rewrite the class in an instrument-agnostic way. 
The absence of the instrument-specific keys should then be processed at the plugin level. 

(this is what TODO at line 37 about?)

**Comment by volodymyrss** [comment]
> Ok. Let's finally decide what is actually the wrong config.

I still suggest to write a test which will at first fail and demonstrate undesirable behavior. Then we can resolve it. And add more keys.
Would that be useful?

> Being instrument-agnostic: what keys beside the data_server_url are strictly necessary, and what are optional?

What is the entire list of keys out of which you are selecting?
Different places use different lists.

Below is the config as loaded in deployment. You should see something similar in your analog of dispatcher/run_analysis (oh, maybe it is available for us to look at?):

```json
{
  "cdci_data_analysis_version": "1.3.1", 
  "config": {
    "dispatcher-config": {
      "cfg_dict": {
        "dispatcher": {
          "dispatcher_port": 8000, 
          "dispatcher_service_url": "http://oda-dispatcher:8000", 
          "dispatcher_url": "0.0.0.0", 
          "products_url": "http://www.astro.unige.ch/cdci/astrooda_"
        }
      }, 
      "origin": {
        "filepath": "/dispatcher/conf/conf_env.yml", 
        "set_by": "command line /cdci_data_analysis/bin/run_osa_cdci_server.py:__main__"
      }
    }, 
    "plugins": {
      "cdci_magic_plugin": {
        "config_file": "/dispatcher/conf/conf.d/magic_data_server_conf.yml"
      }, 
      "cdci_osa_plugin": {
        "config_file": "/dispatcher/conf/conf.d/osa_data_server_conf.yml"
      }, 
      "cdci_spiacs_plugin": {
        "config_file": "/usr/local/lib/python3.8/site-packages/cdci_spiacs_plugin/config_dir/data_server_conf.yml"
      }
    }
  }, 
}
```
here are the keys in the config (I put a bit of annotation):

https://github.com/oda-hub/dispatcher-chart/blob/master/conf/conf_env.yml.example

> 
> Then I have an idea. I can rewrite the class in an instrument-agnostic way.
> The absence of the instrument-specific keys should then be processed at the plugin level.

This does not sound like a bad idea, but it's hard to say for sure until you implement an example, and myself as well as @burnout87 will appreciate it.

> 
> (this is what TODO at line 37 about?)

yes indeed. 

for the reference, [link to line 37 of the implied file](https://github.com/oda-hub/dispatcher-app/blame/093c061562ee67ba08a06afef6351763820c1198/cdci_data_analysis/configurer.py#L37)

**Comment by dsavchenko** [comment]
> Below is the config as loaded in deployment.
Method in question deals with data server config options, like in e.g. osa_data_server_conf.yml, not conf_env.yml
To handle this config there is ConfigEnv class in the same file.  

I implemented what I am talking about. I will make PR when resolve merge conflict

**Comment by dsavchenko** [comment]
See #29

**Comment by volodymyrss** [comment]
> > Below is the config as loaded in deployment.
> 
> Method in question deals with data server config options, like in e.g. osa_data_server_conf.yml, not conf_env.yml

indeed! that is why osa_data_server_conf.yml is also mentioned in the cited dump. Maybe it be good to trace and output it's content.

> To handle this config there is ConfigEnv class in the same file.
> 
> I implemented what I am talking about. I will make PR when resolve merge conflict
