### ISSUE TITLE
I've broke history of 'master'

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/dispatcher-app#282]
I've accidentally pushed to master instead of a branch, when trying to revert I've pushed my local master. The files in HEAD are proper, but it seems that the history tracks also the master of my fork.
Please, force-push proper master from your local repo.
Sorry for this

**Comment by burnout87** [comment]
Ok no problem.

But can the last commit (which is you push) simply be reverted?

**Comment by volodymyrss** [comment]
> Ok no problem.
> 
> But can the last commit (which is you push) simply be reverted?

It can not be. I will take care of it.

**Comment by volodymyrss** [comment]
I did not really have the last master checkout out. But I can see in github's "reflog" that the state before history rewrite was:

```
commit bbc55f8071a761f3bb2f2b0003e4ea521f09e4c9 (HEAD)
Author: Denys <speleoden@gmail.com>
Date:   Sun Nov 21 22:39:33 2021 +0100

    set empty sentry client

commit c8b88a17c6f0fdf7c9dfe05fb619319255a7f58a
Author: Denys <speleoden@gmail.com>
Date:   Sun Nov 21 22:37:51 2021 +0100

    add test for empty sentry config

commit a0f23233d09b0aa203801e15fa8f20b554cf30b8 (origin/master, master)
Merge: 9593ae7 b546bcf
Author: Gabriele Barni <burnout87@users.noreply.github.com>
Date:   Fri Nov 12 19:23:21 2021 +0100

    Merge pull request #254 from oda-hub/time-param-default-conversion
    
    default conversion for time, default t_format, some test adaption

```

So I revert master to `a0f23233d` which I found in another active branch.

You also created `empty-sentry-bugfix`, did you mean it to exist here, or keep in your own repo? If you did not mean, please delete.

**Comment by volodymyrss** [comment]
@burnout87  please check if `a0f23233d` is actually the tip of the master on which you were merging. Also please check that the PR shows what you expect.

**Comment by volodymyrss** [comment]
It does not track your master anymore, @dsavchenko , I think: https://github.com/oda-hub/dispatcher-app/network

**Comment by volodymyrss** [comment]
> I've accidentally pushed to master instead of a branch, when trying to revert I've pushed my local master. The files in HEAD are proper, but it seems that the history tracks also the master of my fork. Please, force-push proper master from your local repo. Sorry for this

We should be more careful of course. But it happens. I fact, I did not myself with one of the other repositories. Luckily github tracks all events, sort of an extended reflog.

**Comment by volodymyrss** [comment]
@burnout87 @dsavchenko  please check this, no development can proceed until we resolve this, since we have to be sure the history on which we merge is as expected.

**Comment by dsavchenko** [comment]
Looks right from what I see

**Comment by burnout87** [comment]
> @burnout87 please check if `a0f23233d` is actually the tip of the master on which you were merging. Also please check that the PR shows what you expect.
> 

Looks ok! PR is consistent
