### ISSUE TITLE
Error while setting input scw_list file from the frontend, content of the temporary directory is ['3c273-2018.txt']

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#292]

**Comment by volodymyrss** [comment]
This is noticed again:

```
Error while setting catalog file from the frontend, content of the temporary directory is ['catalog_rev1512_10sig.txt']
file format for catalog not valid
```

Actually, maybe this is just because of wrong catalog format.
User should be notified adequately.

**Comment by volodymyrss** [comment]
I confirm that this happens with bad format.
A sentry error and a message like this:

![image](https://user-images.githubusercontent.com/3909535/144226274-51196440-852b-4d20-9bc3-f3f6dc36b0aa.png)

Instead, there should be no sentry error, and the response should be about this being wrong format catalog (RequestNotUnderstood, something like that).

**Comment by burnout87** [comment]
gonna work on it now

**Comment by burnout87** [comment]
already better

![image](https://user-images.githubusercontent.com/3757833/144254618-2c925a56-5904-46b4-958a-bbee73617f4f.png)

**Comment by volodymyrss** [comment]
Nice! Maybe good to point out what format precisely is accepted: "fits table (standard OSA catalog) "
Maybe even add which fields are needed in there. How exactly is the catalog parsed?

**Comment by burnout87** [comment]
> Nice! Maybe good to point out what format precisely is accepted: "fits table (standard OSA catalog) " Maybe even add which fields are needed in there. How exactly is the catalog parsed?

Good idea, could you please list me those fields? Not being familioar with catalogs I don't know what the user should know. Perhaps is there a doc or manual I can refer to?

**Comment by volodymyrss** [comment]
> > Nice! Maybe good to point out what format precisely is accepted: "fits table (standard OSA catalog) " Maybe even add which fields are needed in there. How exactly is the catalog parsed?
> 
> Good idea, could you please list me those fields? Not being familioar with catalogs I don't know what the user should know. Perhaps is there a doc or manual I can refer to?

How exactly is the catalog parsed? Where? You have that line. Give me please the line.

**Comment by burnout87** [comment]
Sorry I didn't read properly you message, the parsing takes place here:

[https://github.com/oda-hub/dispatcher-app/blob/30dd4a13634e9c55500923a81df3746b1ed0a925/cdci_data_analysis/analysis/instrument.py#L554-L582](https://github.com/oda-hub/dispatcher-app/blob/30dd4a13634e9c55500923a81df3746b1ed0a925/cdci_data_analysis/analysis/instrument.py#L554-L582)

**Comment by volodymyrss** [comment]
it should be here that it breaks: https://github.com/oda-hub/dispatcher-app/blob/30dd4a13634e9c55500923a81df3746b1ed0a925/cdci_data_analysis/analysis/instrument.py#L567

which reads table in here and checks columns.

We can just say:

```
Catalog should be a FITS (typical standard OSA catalog) or <a href=https://docs.astropy.org/en/stable/api/astropy.io.ascii.Ecsv.html>ECSV</a> table.
```

**Comment by burnout87** [comment]
better now

![image](https://user-images.githubusercontent.com/3757833/144280268-4b887bff-cfa3-4ff9-b5b0-349505a6a59d.png)

**Comment by volodymyrss** [comment]
> better now
> 
> ![image](https://user-images.githubusercontent.com/3757833/144280268-4b887bff-cfa3-4ff9-b5b0-349505a6a59d.png)

Very nice!

Just that:

`this should be a ...` => `it should be a ..` or `catalog should be provided in a`

**Comment by burnout87** [comment]
used the same approach also for an unformatted scw list

![image](https://user-images.githubusercontent.com/3757833/144453825-ae8789fa-493e-45a3-810a-f11d8548fc3c.png)
