### ISSUE TITLE
default selected catalog is empty and can not be parsed by the frontend

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#314]
e.g. this was generated:

[www.astro.unige.ch/mmoda/?DEC=-29.74516667&E1_keV=20&E2_keV=40&RA=265.97845833&T1=2017-03-06T13%3A26%3A48.0&T2=2017-03-06T15%3A32%3A27.0&T_format=isot&detection_threshold=7&image_scale_max=&image_scale_min=&instrument=isgri&integral_data_rights=public&max_pointings=50&osa_version=OSA11.1&product_type=isgri_image&query_status=new&query_type=Real&radius=15&src_name=1E%201740.7-2942](https://www.astro.unige.ch/mmoda/?DEC=-29.74516667&E1_keV=20&E2_keV=40&RA=265.97845833&T1=2017-03-06T13%3A26%3A48.0&T2=2017-03-06T15%3A32%3A27.0&T_format=isot&detection_threshold=7&image_scale_max=&image_scale_min=&instrument=isgri&integral_data_rights=public&max_pointings=50&osa_version=OSA11.1&product_type=isgri_image&query_status=new&query_type=Real&radius=15&selected_catalog=&src_name=1E%201740.7-2942)

it occurs here http://cdciweb02.isdc.unige.ch/mmoda/gallery/node/874

frontend may be made to parse these, but alternatively dispatcher may be made to generate something consumable by the frontend in this case.

Second option seems kind of better, but barely. What do you think?

**Comment by burnout87** [comment]
I wanted to start working on this, is it related to [https://github.com/oda-hub/frontend-astrooda/issues/119](https://github.com/oda-hub/frontend-astrooda/issues/119)?

**Comment by volodymyrss** [comment]
partially. Could you check that the URL above works on frontend dev? After substituting prod to dev site of course.

**Comment by burnout87** [comment]
Checked now, on dev I managed to start the request. I could also see the change in the code
