### ISSUE TITLE
would be nice to restrict the tests so they do not take 1hr every time...

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#317]
maybe introduce another label-controlled division

but I wonder which ones are slow

**Comment by burnout87** [comment]
It's hard to say which ones are the slowest, but there are some that are (very) bug, and take quite some time too complete:

Example: [https://github.com/oda-hub/dispatcher-app/blob/81fc90d1a5d93d1b65ea397a732b9d7f905a94b9/tests/test_job_management.py#L1598-L1613](test_email_scws_list).

Cases like these can be marked/labelled as slow, and perhaps not being executed in certain cases (for example, when it is not necessary). A label-base approach could help I think
