### ISSUE TITLE
see what to do with drupal unconventional time format (e.g. 2018-31-12T23:59:59), it might pop up somewhere 

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#329]
e.g. `/mmoda-pg/observations/range/2018-31-12T23%3A59%3A59--2021-01-12T00%3A00%3A0`

despite that in the views, the format will be set to ISOT.

**Comment by burnout87** [comment]
The more I try to investigate, the more I am convinced that there is some bug in the module I am using, and therefore it's no reliable.

I am exploring other options.

**Comment by burnout87** [comment]
I am also noticing all those new observations created, when that should not happen...

**Comment by volodymyrss** [comment]
Yeap. Well, I created a bunch of real images, looks go as far as as it can be now http://cdciweb02.isdc.unige.ch/mmoda/gallery/data-products-gallery
