### ISSUE TITLE
exception when posting

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#330]
this is in the log:

```
the requested url http://cdciweb02.internal.odahub.io/mmoda/gallery/node lead to the error {"message":"Type http:\/\/cdciweb02.internal.odahub.io\/mmoda\/gallery\/rest\/type\/node\/observation does not correspond to an entity on this site."}, this might be due to an error in the url or the page requested no longer exists, please check it and try to issue again the request
```

edit: note that this did not produce a sentry, and it should have, assuming it's not a usage problem. And if it's a usage problem user should get a message.

**Comment by burnout87** [comment]
that's really weird, all the tests I am running so far are passing

**Comment by volodymyrss** [comment]
this happens when I run https://github.com/oda-hub/oda_api/blob/upload-gallery-example/doc/source/user_guide/UploadToGallery.ipynb

**Comment by volodymyrss** [comment]
#
