### ISSUE TITLE
 Angle parameter gets converted to degrees when passing to backend

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/dispatcher-app#334]
As an example, this
https://github.com/oda-hub/dispatcher-plugin-legacysurvey/blob/b1fee836889b530380c1fe1556fe7e2d1e9f395b/dispatcher_plugin_legacysurvey/queries.py#L143
parameter when set to 3. in the frontend becomes 0.05 in param_dict here 
https://github.com/oda-hub/dispatcher-plugin-legacysurvey/blob/b1fee836889b530380c1fe1556fe7e2d1e9f395b/dispatcher_plugin_legacysurvey/queries.py#L153
but I expect it not to convert unless get_value_in_default_format() is explicitly called.

As we can see from test https://github.com/oda-hub/dispatcher-app/blob/15b294af455f754ed5c986d76a636f88d1b4ba28/tests/test_unit.py#L130
the Angle class itself works well. 

I suspect that unintended conversion happens when setting dict here https://github.com/oda-hub/dispatcher-app/blob/15b294af455f754ed5c986d76a636f88d1b4ba28/cdci_data_analysis/analysis/instrument.py#L149 and then the values are somehow    
pushed back to the Parameter objects. At this point, I am a bit lost.
@burnout87 @volodymyrss you were working with the units of parameters recently, can you help?

**Comment by burnout87** [comment]
Which parameter is giving you issues? `pixel_size`?

**Comment by volodymyrss** [comment]
Could you @dsavchenko please demonstrate the effect in a test?

**Comment by dsavchenko** [comment]
> Which parameter is giving you issues? `pixel_size`?
> 
> I don't understand why from a value of 3. (which is in arc_sec I guess) you get a value of 0.05 when a conversion to a default format is applied.

Sorry. This one becomes 0.0008(3) of course

**Comment by dsavchenko** [comment]
> Could you @dsavchenko please demonstrate the effect in a test? 

I should think again, how to properly construct such a test

**Comment by burnout87** [comment]
also, at which step do you notice that the value is not the one you were expecting?

**Comment by dsavchenko** [comment]
> also, at which step do you notice that the value is not the one you were expecting?

I noticed a very strange and cryptic exception in the backend of legacysurvey. After spending a few hours on that I finally realised that the values of some parameters passed to the backend are not the same as being set in the frontend.

What's interesting, is that it was working some time ago.

**Comment by burnout87** [comment]
> 
> What's interesting, is that it was working some time ago.

We applied a change regarding the way default values of parameters are assigned, and also when. This probably is the reason why of this confusion.

Is it a problem if the value is converted in degree?

**Comment by dsavchenko** [comment]
> Is it a problem if the value is converted in degree?

Yes, because the backend may expect values in other units. The hotfix may be to change the backend, but for the general case (especially our goal of generic nb plugin) it should be fixed.

**Comment by volodymyrss** [comment]
I did not look deeply, I would imagine adapting units and formats for consumption by the backend is one of the key functions of the plugin. Of course, plugin should be give values together with units by the dispatcher.

**Comment by burnout87** [comment]
I agree, is this a change that can be easily applied to the plugin?

**Comment by volodymyrss** [comment]
We should make it clear for @dsavchenko how to get both the value and the units of the parameter. Is there a place in other plugin we can point out quickly?

**Comment by burnout87** [comment]
In these two lines, the two time parameters are explicitly formatted in `ISOT` format:

[https://github.com/oda-hub/dispatcher-plugin-integral/blob/e80d2c0098c4fdb68f1aaee90de8f213fc09cfef/cdci_osa_plugin/osa_dataserve_dispatcher.py#L603-L604](https://github.com/oda-hub/dispatcher-plugin-integral/blob/e80d2c0098c4fdb68f1aaee90de8f213fc09cfef/cdci_osa_plugin/osa_dataserve_dispatcher.py#L603-L604)

And here instead `RA` and `DEC`, that are two angles, are set in te catalog explicitly in `deg` unit:

[https://github.com/oda-hub/dispatcher-plugin-integral/blob/e80d2c0098c4fdb68f1aaee90de8f213fc09cfef/cdci_osa_plugin/osa_dataserve_dispatcher.py#L644-L645](https://github.com/oda-hub/dispatcher-plugin-integral/blob/e80d2c0098c4fdb68f1aaee90de8f213fc09cfef/cdci_osa_plugin/osa_dataserve_dispatcher.py#L644-L645)

So, in your case, we can extract the value of the parameter `pixel_size` as arcsec, for example like so:

``` Python
instrument.get_par_by_name('pixel_size')._astropy_angle.arcsec
```

Hope this helps, in any case, we can also discuss directly together and see if we find a better solution.

**Comment by dsavchenko** [comment]
> ```python
> instrument.get_par_by_name('pixel_size')._astropy_angle.arcsec
> ```

Thanks! I will stick to this as a more-or-less universal hotfix.
And yes, let's discuss it in the future.

**Comment by dsavchenko** [comment]
> Thanks! I will stick to this as a more-or-less universal hotfix.

It doesn't work. The value of the parameter _astropy_angle is wrong. 
I will try to create a test and to investigate further

**Comment by burnout87** [comment]
> 
> It doesn't work. The value of the parameter _astropy_angle is wrong. It is not returning the value in degrees, but the value is overwritten with wrongly defined units. I will try to create a test and to investigate further

Yes that will help.

**Comment by dsavchenko** [comment]
See test in #335

**Comment by burnout87** [comment]
Ok, I see the problem, I will investigate further.
