### ISSUE TITLE
`job manager` role should be sufficient to manage jobs

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#343]
right now it's kind of useless. `administrators` can set any roles anyway.

**Comment by burnout87** [comment]
I have a suspect, the output I am getting is the following:

```
Your privilege roles include ['authenticated user', 'user manager', 'general', 'integral-private-qla', 'magic', 'unige-hpc-full', 'public-pool-hpc', 'antares', 'sdss', 'apc', 'bitp', 'jobs manager', 'gallery contributor'], but the following roles are missing: administrator.
```

But the two required roles should be: 
[https://github.com/oda-hub/dispatcher-app/blob/cf9a4fb6f51eb6b928b720d5df2f55aaea1ad4db/cdci_data_analysis/flask_app/dispatcher_query.py#L347](https://github.com/oda-hub/dispatcher-app/blob/cf9a4fb6f51eb6b928b720d5df2f55aaea1ad4db/cdci_data_analysis/flask_app/dispatcher_query.py#L347)

And I have the, old, `jobs manager` role, but it's not telling me that I am lacking also the `job manager` role.

**Comment by volodymyrss** [comment]
ok, please regenerate token

**Comment by burnout87** [comment]
ok now the error output is correct

**Comment by volodymyrss** [comment]
the role in the frontend was jobs manager

**Comment by burnout87** [comment]
This is the error I get:

```Bash
Your privilege roles include ['authenticated user', 'user manager', 'general', 'integral-private-qla', 'magic', 'unige-hpc-full', 'public-pool-hpc', 'antares', 'sdss', 'apc', 'bitp', 'job manager', 'gallery contributor'], but the following roles are missing: administrator, jobs manager.
```

**Comment by volodymyrss** [comment]
still? So it is not correct?

**Comment by burnout87** [comment]
I have the appropriate role, but it is saying the wrong one is missing.

**Comment by volodymyrss** [comment]
what about on staging?

**Comment by burnout87** [comment]
ok from staging it works

**Comment by volodymyrss** [comment]
could you check how it is in currently deployed tag?

**Comment by burnout87** [comment]
yes, also there, the output is the expected one
