### ISSUE TITLE
strange error with spiacs in dispatcher

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#359]
![image](https://user-images.githubusercontent.com/3909535/154253293-38b65cf6-08df-435e-9d63-d8e732852f6c.png)

**Comment by burnout87** [comment]
It was me...

![image](https://user-images.githubusercontent.com/3757833/154254659-46884472-c546-422e-b6d4-a0cc7e53f458.png)

**Comment by volodymyrss** [comment]
So we do not know why?.. is it because dummy?

**Comment by burnout87** [comment]
Most likely the dummy product is missing. It is searched here:

[https://github.com/oda-hub/dispatcher-plugin-integral-all-sky/blob/d82febb053047dbf12310a4493a555340f65059a/dispatcher_plugin_integral_all_sky/spiacs_lightcurve_query.py#L376-L400](https://github.com/oda-hub/dispatcher-plugin-integral-all-sky/blob/d82febb053047dbf12310a4493a555340f65059a/dispatcher_plugin_integral_all_sky/spiacs_lightcurve_query.py#L376-L400)
