### ISSUE TITLE
`resolve_source` endpoint not deployed on staging

### ISSUE THREAD

**Issue by burnout87** [oda-hub/dispatcher-app#371]
This endpoint is not available when I try to use it.

It has been implemented with #369

**Comment by volodymyrss** [comment]
please check, to be sure.

**Comment by burnout87** [comment]
I still get the same error

**Comment by volodymyrss** [comment]
the version which is currently deployed has the latest commit, from 7 days ago. I just re-deployed it, not sure it changes anything.
I suggest we change the version of the app, the one returned here:

https://frontend.staging.odahub.io/mmoda/dispatch-data/run_analysis

it's in cdci_data_analysis/pkg_info.json

that way we can see explicitly what's the version

**Comment by burnout87** [comment]
Ok, I see the problem, the endpoint is there and working, but some configuration is missing, namely `name_resolver_url` and `entities_portal_url` .

Those should be:
``` language:yml
name_resolver_url: "http://cdsweb.u-strasbg.fr/cgi-bin/nph-sesame/-oxp/NSV?"
entities_portal_url: "http://cdsportal.u-strasbg.fr/?target={}"
```

**Comment by burnout87** [comment]
> could you make them fall-back on these by default? I suppose the parsing is tuned to their output? so making them configurable without some modularity is only so much useful.
> 

Ok I will implement that.

> By the way, you could use proxy resolver, which also uses and merges other sources, not available in simbad. Like so:
> 
> [https://resolver-prod.obsuks1.unige.ch/api/v1.1/byname/{}](https://resolver-prod.obsuks1.unige.ch/api/v1.1/byname/%7B%7D)
> 
> 
> It's what is used in frontend.
> 
frontend actually attempts first to query this resolver, and if this fails then it moves on to try the one I am currently using

> 
> I note that your might need other properties but time/location, so moving to internal resolver could be another stage. For now, please just set the defaults to what you expect.

Indeed it might need some further development, so first stage is to apply the defaults, then will extend also with the usage of the other resolver

**Comment by volodymyrss** [comment]
> > could you make them fall-back on these by default? I suppose the parsing is tuned to their output? so making them configurable without some modularity is only so much useful.
> 
> Ok I will implement that.
> 
> > By the way, you could use proxy resolver, which also uses and merges other sources, not available in simbad. Like so:
> > [https://resolver-prod.obsuks1.unige.ch/api/v1.1/byname/{}](https://resolver-prod.obsuks1.unige.ch/api/v1.1/byname/%7B%7D)
> > It's what is used in frontend.
> 
> frontend actually attempts first to query this resolver, and if this fails then it moves on to try the one I am currently using

sure, but using simbad is a hard fallback - it misses half of what we need. Let's be clear about it. 
And I think we should remove this fallback - when it happens its confusing, since only somethings work suddenly. The internal proxy resolver should be considered critical component and not fail.

> 
> > I note that your might need other properties but time/location, so moving to internal resolver could be another stage. For now, please just set the defaults to what you expect.
> 
> Indeed it might need some further development, so first stage is to apply the defaults, then will extend also with the usage of the other resolver

Extending the usage to two options would lead to partially, unpredictably working service. It's the kind of case when it's better to produce nothing than produce unpredictable result. Here, it's even worse than in the frontend.
So defaults - simbad - will be good for now.
Then - it should be only internal.
Logic of combining different resolvers and seeing what's right should be completely in a separate component - the proxy resolver.
However, it could be useful to have a switch between two modes: internal resolver and simbad.

also, it's be good to track "resolved by" somehow. It will be useful later.

**Comment by volodymyrss** [comment]
Please close as suitable.

**Comment by burnout87** [comment]
Do you think it is a good idea to integrate, in the future, the resolver I initially implemented (ie http://cdsweb.u-strasbg.fr/cgi-bin/nph-sesame/-oxp/NSV?), within our local one ? Perhaps as an additional plugin...

**Comment by volodymyrss** [comment]
It is already used https://github.com/oda-hub/oda-resolver/blob/master/tnr/plugins/sesameproxy.py

**Comment by burnout87** [comment]
Ok I see, it is also used as a fallback on the frontend.

**Comment by volodymyrss** [comment]
> Ok I see, it is also used as a fallback on the frontend.

which is a bit unfortunate. But it will do for now.

**Comment by burnout87** [comment]
In the meantime, I just checked and `resolve_name` is now working as expected. this can be closed.
