### ISSUE TITLE
"Done" email not received if token expires between submission and completion

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/dispatcher-app#376]
On 29.03.2022, I submitted 14 jobs, some completed, but I have never received a completion message, as my token expired in the meanwhile. Most are still running.

**Comment by volodymyrss** [comment]
It's in part intended: job has to have limited lifetime. Else who knows what will happen with a token given to the job.
But, we should give the job another token on submission, this was anticipated #212 . So that the lifetime starts when the job is sent. Let's continue in #212
