### ISSUE TITLE
clone gitlab/renku repo duplicated in fixtures?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#377]
The staging renku integration does not work. It broke in one of the PRs in the last month, I did not follow enough.
I tried to see if the test works, but found that the clone function is copied in the tests:

https://github.com/oda-hub/dispatcher-app/blob/c6091d0198b2ec4d317ce13fcf4def084464dc4f/cdci_data_analysis/pytest_fixtures.py#L770-L783

While the one which is used is this one:

https://github.com/oda-hub/dispatcher-app/blob/c6091d0198b2ec4d317ce13fcf4def084464dc4f/cdci_data_analysis/analysis/renku_helper.py#L102-L116

So what's tested is not used.
Why would it be so, do you know @burnout87?

After this test works with the code which is actually used in the application, it will be necessary to have some more log about the ssh key (and other parameters) used.

**Comment by burnout87** [comment]
the tests work for me after applying the fix  in #378, would you give it a try and see if the tests pass with that?

**Comment by volodymyrss** [comment]
> the tests work for me after applying the fix in #378, would you give it a try and see if the tests pass with that?

I would check, but could you help me understand why an older version of the clone function is copied in the tests? This way the function which is used live is not tested. So if I understand correctly, the test is not too useful, no?

**Comment by burnout87** [comment]
> I would check, but could you help me understand why an older version of the clone function is copied in the tests?

Unless I understood  wrong, the difference is related to the git_ssh command, which was changed with #365 , but not in the test. 

Also I changed the names of the renku-relaterd configurations, was this change applied on the staging?

**Comment by volodymyrss** [comment]
> > I would check, but could you help me understand why an older version of the clone function is copied in the tests?
> 
> Unless I understood wrong, the difference is related to the git_ssh command, which was changed with #365 , but not in the test.

But why can't you just `from cdci_data_analysis.analysis.renku_helper import clone..repo`? That way you test it. 
This function should not have been copied, but imported. Or was there a special reason to copy it?
Copying leads precisely to the kind issue we have: the two copies diverged, and we are not testing the function used live.

> Also I changed the names of the renku-relaterd configurations, was this change applied on the staging?

you can see the list of staging deployments in the mattermost. So presumably yes.

**Comment by burnout87** [comment]
> > > I would check, but could you help me understand why an older version of the clone function is copied in the tests?
> > 
> 
> But why can't you just `from cdci_data_analysis.analysis.renku_helper import clone..repo`? That way you test it. This function should not have been copied, but imported. Or was there a special reason to copy it? Copying leads precisely to the kind issue we have: the two copies diverged, and we are not testing the function used live.
> 

The test now uses and tests it

> 
> you can see the list of staging deployments in the mattermost. So presumably yes.

I checked here: [https://frontend-staging.obsuks1.unige.ch/mmoda/dispatch-data/run_analysis](https://frontend-staging.obsuks1.unige.ch/mmoda/dispatch-data/run_analysis) and I can see that the config is not updated

**Comment by volodymyrss** [comment]
> 
> > you can see the list of staging deployments in the mattermost. So presumably yes.
> 
> I checked here: https://frontend-staging.obsuks1.unige.ch/mmoda/dispatch-data/run_analysis and I can see that the config is not updated

I do not quite understand, what do you expect to see in there? There are several things combined in this output. Could you point to the repo/revision the updated config should come?

**Comment by burnout87** [comment]
> 
> For that, could you add sufficient log to see where these options are taken?

There is already some logging here:

[https://github.com/oda-hub/dispatcher-app/blob/c6091d0198b2ec4d317ce13fcf4def084464dc4f/cdci_data_analysis/flask_app/app.py#L273-L275](https://github.com/oda-hub/dispatcher-app/blob/c6091d0198b2ec4d317ce13fcf4def084464dc4f/cdci_data_analysis/flask_app/app.py#L273-L275)
