### ISSUE TITLE
renku push is sometimes failing for existing branches

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#379]
maybe it should be force-push

**Comment by burnout87** [comment]
This is unexpected because in case of existing branch it should return the url, I also wrote a test that covers this specific case.

Which kind of error did you see? Because I just tried to push on Renku after the very same request, and it didn't complain.

**Comment by volodymyrss** [comment]
well it does. Maybe conflicts with existing older versions of the branch.
Are there any disadvantages of force-push?
Also, we should auto-cleanup old branches.

**Comment by burnout87** [comment]
> well it does. Maybe conflicts with existing older versions of the branch. 
Well this could be, though I was not expecting this to happen, especially because I developed everything on a separate personal test repository, but appareantly...

> Are there any disadvantages of force-push? 
No not all, I will implement it.
