### ISSUE TITLE
start renku session with the notebook opened

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#381]
This requires renku feature.  @rokroskar , if you have an open ticket for this, let us know!

**Comment by volodymyrss** [comment]
@rokroskar so there is an issue for this, yes?

**Comment by burnout87** [comment]
This is it:

https://github.com/SwissDataScienceCenter/renku-ui/issues/1781

It was shared within the slack channel

**Comment by volodymyrss** [comment]
Is this done with https://github.com/oda-hub/dispatcher-app/pull/417, @burnout87 ?
