### ISSUE TITLE
a7bb5f06f853f9c4 had 3 done emails, and attachements were not sent

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#386]
the log:

```
session_id GTT4PNKA03J546F1 job_id a7bb5f06f853f9c4 2022-04-11 21:16:57.509377
    -  {'ctime': [1649704565.9603653], 'ctime_isot': '2022-04-11T19:16:05', 'fn': 'scratch_sid_GTT4PNKA03J546F1_jid_a7bb5f06f853f9c4/email_history/attachments'}
    -  {'ctime': [1649704558.4476347], 'ctime_isot': '2022-04-11T19:15:58', 'fn': 'scratch_sid_GTT4PNKA03J546F1_jid_a7bb5f06f853f9c4/email_history/email_done_1649704543.8820796.email'}
    -  {'ctime': [1649702088.5516853], 'ctime_isot': '2022-04-11T18:34:48', 'fn': 'scratch_sid_GTT4PNKA03J546F1_jid_a7bb5f06f853f9c4/email_history/email_submitted_1649702079.3681464.email'}
    -  {'ctime': [1649704566.3444026], 'ctime_isot': '2022-04-11T19:16:06', 'fn': 'scratch_sid_GTT4PNKA03J546F1_jid_a7bb5f06f853f9c4/email_history/email_done_1649704553.306419.email'}
    -  {'ctime': [1649704557.2395172], 'ctime_isot': '2022-04-11T19:15:57', 'fn': 'scratch_sid_GTT4PNKA03J546F1_jid_a7bb5f06f853f9c4/email_history/email_done_1649704543.3353653.email'}
```

the problem is probable here:

https://github.com/oda-hub/dispatcher-app/blob/91dab3f48b6c9615a89eaa97701ee1a92d46e0c5/cdci_data_analysis/analysis/email_helper.py#L385

if `status` is `done` with `run_query`. Actual status should be used in this function, not always "submitted".

Attachment is a different issue, and should be logged more to understand what's the issue.

**Comment by burnout87** [comment]
So, was in this case the status `done` returned with `run_query`? Then in that case no email should be sent because the status has to be `submitted`.

**Comment by volodymyrss** [comment]
> So, was in this case the status `done` returned with `run_query`? Then in that case no email should be sent because the status has to be `submitted`.

"the status has to be submitted" is an assumption which is not enforced.
There can be situation when this happens, due to some race conditions.
It should be enforced that the status is `submitted`. And if it is not `submitted`, something defined should happen, specifically a sentry alert.

**Comment by volodymyrss** [comment]
Ok, I did not look close. Maybe it's not exactly that.
Anyway, there should be sentry error when there is a `done` status in run_query.

In addition, maybe we can add to the file stored in email_history some information about what triggered it exactly. And even summary of the other conditions. That will help to debug and  will be visible in /inspect call.

**Comment by burnout87** [comment]
> there should be sentry error when there is a `done` status in run_query.

Ok that is quite straightforward to add.

> 
> In addition, maybe we can add to the file stored in email_history some information about what triggered it exactly. And even summary of the other conditions. That will help to debug and will be visible in /inspect call.

For example, we can have a log file, logging each email sending attempt, containing those information for each "trigger".

**Comment by volodymyrss** [comment]
> > there should be sentry error when there is a `done` status in run_query.
> 
> Ok that is quite straightforward to add.
> 
> > In addition, maybe we can add to the file stored in email_history some information about what triggered it exactly. And even summary of the other conditions. That will help to debug and will be visible in /inspect call.
> 
> For example, we can have a log file, logging each email sending attempt, containing those information for each "trigger".

Yeah, something like that.
