### ISSUE TITLE
exception when performing a request to the product gallery: RequestNotAuth?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#390]
![image](https://user-images.githubusercontent.com/3909535/165339011-7ca4b39e-2d55-44f9-a05b-ad058ef63f93.png)

**Comment by burnout87** [comment]
This is likely related to the known issue of not managing to complete a request towards the gallery, documented here https://gitlab.astro.unige.ch/oda/product-gallery/doc/-/issues/8 .

When #396 will be done, we will have more details in case this situation happens again.
