### ISSUE TITLE
make an incident-report endpoint

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#393]
stricktly from authentifed users

sending an email stricktly to predefined email addresses

**Comment by burnout87** [comment]
Besides the fact the more users can received these information, what would the advantages be compared to sending a sentry? 

will it ideally replace it?

**Comment by volodymyrss** [comment]
This is just for the users. Users will not have access to sentry.

In fact, the dispatcher should make a sentry alert on request to this endpoint.
