### ISSUE TITLE
design non-volatile product id to encompas multiple job IDs

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#406]
let's discuss!

**Comment by burnout87** [comment]
A set of parameters will have to be defined, depending on the use-case: this will be used to generate a `product_id` to use for identifying a data-product over the gallery when we need perform an update.

**Comment by burnout87** [comment]
https://github.com/oda-hub/dispatcher-app/pull/407
https://github.com/oda-hub/oda_api/pull/139
