### ISSUE TITLE
Write in email if a job has completed but did not produce a useful result

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/dispatcher-app#409]
Currently all jobs are completed, some with error. "Ready" is not quite the right word for this.

There is an issue on dispatcher to fetch the results and give more feedback. Its somewhat straightforward. But please make another one, on dispatcherapp.

V

On 10 Jun 2022 18:00, Carlo Ferrigno <carlo.ferrigno@unige.ch> wrote:

    Hi,

    this job naturally failed as not all science windows are present, but the email does not mention it.

    I think that if a job failed the email should be sent with the error message, not with a generic "done" message.

    Carlo

    On 10.06.22 16:51, [postmaster@in.odahub.io](mailto:postmaster@in.odahub.io) wrote:

        Dear User,

        you receive this message because at 2022-06-10 16:49:09 ( 2.6 minutes ago ) you submitted a request
        for a isgri_image from the service provided by University of Geneva
        available at the URL https://www.astro.unige.ch/mmoda/.

        Your request is now ready.

        You can inspect the status of your job using the following[ url](https://www.astro.unige.ch/mmoda//dispatch-data/resolve-job-url?job_id=983784403eef0e41&session_id=9YIKTG0JJ9SLR5HA&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJDYXJsby5GZXJyaWdub0B1bmlnZS5jaCIsImVtYWlsIjoiQ2FybG8uRmVycmlnbm9AdW5pZ2UuY2giLCJuYW1lIjoiY2ZlcnJpZ25vIiwicm9sZXMiOiJhdXRoZW50aWNhdGVkIHVzZXIsIGFkbWluaXN0cmF0b3IsIHVzZXIgbWFuYWdlciwgY29udGVudCBtYW5hZ2VyLCBnZW5lcmFsLCBpbnRlZ3JhbC1wcml2YXRlLXFsYSwgbWFnaWMsIHVuaWdlLWhwYy1mdWxsLCBwdWJsaWMtcG9vbC1ocGMsIGFudGFyZXMsIHNkc3MsIHJlbmt1IGNvbnRyaWJ1dG9yLCBnYWxsZXJ5IGNvbnRyaWJ1dG9yIiwiZXhwIjoxNjU1MDQwNjM3fQ.DfFBXTaMumWfqX6I1VL5_iMiTB_kJDLe4hqJdAXYdeA).
        Note that this url is NOT permanent, and will be valid until 2022-06-12 15:30:37.
        Such link is intended for the recipient of this email, please do NOT share it, since this might contain sensitive information.

        You can also retrieve the result by repeating the request (either with frontend or with the python API query at the end of this message.).

        In case you have questions or issues you can contact us at[ this email](mailto:contact@odahub.io) or reply to the current message.

        Kind regards,

        The ODA team.

        Python API code:

        from oda_api.api import DispatcherAPI

        disp = DispatcherAPI(url=["https://www.astro.unige.ch/mmoda//dispatch-data"](https://www.astro.unige.ch/mmoda//dispatch-data), instrument="mock")

        par_dict = {
        "DEC": -45.05405,
        "E1_keV": 28.0,
        "E2_keV": 40.0,
        "RA": 134.59029,
        "T1": "2017-03-06T13:26:48.000",
        "T2": "2017-03-06T15:32:27.000",
        "T_format": "isot",
        "api": "True",
        "detection_threshold": 7.0,
        "instrument": "isgri",
        "integral_data_rights": "all-private",
        "max_pointings": 50,
        "oda_api_version": "1.1.28",
        "off_line": "False",
        "osa_version": "OSA11.2",
        "product": "isgri_image",
        "product_type": "Real",
        "radius": 15.0,
        "scw_list": [
        "251200600010.000",
        "251200610010.000",
        "251200620010.000",
        "251200630010.000",
        "251200640010.000",
        "251200650010.000",
        "251200660010.000",
        "251200670010.000",
        "251200680010.000",
        "251200690010.000",
        "251200700010.000",
        "251200710010.000",
        "251200720010.000",
        "251200730010.000",
        "251200740010.000",
        "251200750010.000",
        "251200760010.000",
        "251200770010.000",
        "251200780010.000",
        "251200790010.000",
        "251200800010.000",
        "251200810010.000",
        "251200820010.000",
        ],
        "src_name": "Gal. Plane, l= 266",

        }

        data_collection = disp.get_product(**par_dict)

        Note that this code contains your private token. Be careful how you share it!
        This token is short-lived, and will expire in 46.6 hours.
        To learn how to get a new token, please refer to [these instructions](imap://ferrigno@outlook.unige.ch:993/fetch%3EUID%3E/INBOX%3E642719).

**Comment by volodymyrss** [comment]
once "done" callback is received, dispatcher can request the backend to get the product. The product can be inspected for detailed exception, and the result can be even previewed in the email. The "preview" functionality: producing short summary of the product, should be part of the plugin, since backends are different.
