### ISSUE TITLE
 "view in renku" for authentified session

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#419]
after we login with renku, we should be able to add "view in renku" for authentified session and pass credentials to access MMODA from the session

follows https://github.com/oda-hub/mmoda-frontend-module/issues/178

**Comment by burnout87** [comment]
so that the Renku credentials will be included in the request to Renku from MMODA?

**Comment by volodymyrss** [comment]
this done now @burnout87 ?

**Comment by burnout87** [comment]
actually the "view in renku" is always visible, and works also for anonymous sessions

**Comment by volodymyrss** [comment]
of course but what this issue is about is passing credentials, see description. ok then it's closed
