### ISSUE TITLE
'Sentry' object has no attribute 'capture'

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#425]
maybe some interface change?

![image](https://user-images.githubusercontent.com/3909535/183437371-f63e9bdf-f709-4908-99dd-16f5c6364c3a.png)

**Comment by burnout87** [comment]
Seems like the methods to be used is `capture_message` (https://docs.sentry.io/clients/python/usage/).

This will have to be used where the `Sentry` object provided by `raven.contrib.flask` is used (eg https://github.com/oda-hub/dispatcher-app/blob/976b93a39a3222d8384e5d2b85e207557eb0de5c/cdci_data_analysis/flask_app/app.py#L16)

Whereas here

https://github.com/oda-hub/dispatcher-app/blob/976b93a39a3222d8384e5d2b85e207557eb0de5c/cdci_data_analysis/flask_app/dispatcher_query.py#L547-L557

It is using the `Sentry` class provided by the `raven` library.

But I am not entirely sure about the difference, and what should be used and why it was designed this way.

Perhaps some refactoring is necessary to make the sentry client usage more consistent? I don't it will take too much time

**Comment by volodymyrss** [comment]
> Seems like the methods to be used is `capture_message` (https://docs.sentry.io/clients/python/usage/).
> 
> This will have to be used where the `Sentry` object provided by `raven.contrib.flask` is used (eg
> 
> https://github.com/oda-hub/dispatcher-app/blob/976b93a39a3222d8384e5d2b85e207557eb0de5c/cdci_data_analysis/flask_app/app.py#L16
> )
> 
> Whereas here
> 
> https://github.com/oda-hub/dispatcher-app/blob/976b93a39a3222d8384e5d2b85e207557eb0de5c/cdci_data_analysis/flask_app/dispatcher_query.py#L547-L557
> 
> It is using the `Sentry` class provided by the `raven` library.
> 
> But I am not entirely sure about the difference, and what should be used and why it was designed this way.
> 
> Perhaps some refactoring is necessary to make the sentry client usage more consistent? I don't it will take too much time

Ok, maybe #426 . But maybe better at first a minimal change, which might also help to see the live problem with message in case of empty product or so.
