### ISSUE TITLE
combine two warning kinds

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#443]
try to avoid always reporting all default parameters for all instruments

**Comment by burnout87** [comment]
Is this related to  https://github.com/oda-hub/oda_api/issues/152

**Comment by volodymyrss** [comment]
> Is this related to [oda-hub/oda_api#152](https://github.com/oda-hub/oda_api/issues/152) ?

it's related.

see how antares returns a warning because T1/T2 are not used.

Similar warning should be sent for every parameter which is not used.

what oda_api does is an independent check. It is not exceedingly useful, but let's keep it for a bit.
Instead, oda_api should make sure to show the warning returned by dispatcher (like frontend does)
