### ISSUE TITLE
add option to disable plugins

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/dispatcher-app#460]

**Comment by volodymyrss** [comment]
the goal is to allow deployments with the same code but reduced instrument set.

could be better to rather add explicitly the plugin list, in some cases.
maybe  even add config options controlling discovery, defaulting to "auto", but allowing to specify the list.


on the other hand, if we keep adding instruments through nb2service plugin only, this is all not going to be too necessary.

**Comment by dsavchenko** [comment]
It's a bit complicated to do this with the config option as far as instrument factory list is being built by importing import.py module (no configuration done so far).
So let's just use environment variable. See #471
