### ISSUE TITLE
unexpected "argument catalog_selected_objects is not used"

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#482]
Looks like a consequence of new comments about unused parameters. But this parameter was added by the dispatcher-forntend interation in the normal flow. Why was it there and not used?

![image](https://user-images.githubusercontent.com/3909535/206280499-079776b4-501f-4784-8ec5-119a42da6efe.png)

**Comment by volodymyrss** [comment]
it might be that it is actually not used which is leading to undesirable results

**Comment by dsavchenko** [comment]
This is the consequence of the new changes. 
What is this argument about? Is it actually somehow processed by the integral backend? If so, it should be added to the plugin. 
Alternatively, allow_unknown_arguments might be set for the entire instrument.

**Comment by volodymyrss** [comment]
It's good that it's noticed.

It's not used directly by the integral backend, but it is used by dispatcher to construct catalog.

https://github.com/oda-hub/dispatcher-app/blob/fc3203586097a9840c2a4ab3a8694f99e2b160d2/cdci_data_analysis/analysis/instrument.py#L718-L723

It might not be ideal that the catalog treatment is in the dispatcher and not plugin. It's historically so because of the need for specialized interaction with frontend (still does not need to be like that).

I guess it should be added to parameters accepted by dispatcher, since it's its own parameter.

**Comment by dsavchenko** [comment]
https://github.com/oda-hub/dispatcher-app/pull/483
