### ISSUE TITLE
make sure the error is comprehensive when renku is down

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#490]
refer to renku status and mmoda status

https://github.com/oda-hub/dispatcher-app/pull/487#issuecomment-1346863673

**Comment by burnout87** [comment]
More specifically, when renkulab is down?

I ask because the push operation towards the gitlab repo might go through without any issue, but still the link might not be working because of indeed renkulab. Does it make sense?

**Comment by volodymyrss** [comment]
> > > More specifically, when renkulab is down?
> > 
> > 
> > If the issue during pushing might be related to renku, add an extra notice with reference to their statuspage.
> 
> Where can I find the link?

https://github.com/oda-hub/dispatcher-app/pull/487#issuecomment-1346445656

**Comment by burnout87** [comment]
This was done, can be closed.
