### ISSUE TITLE
unable to open renku session

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#491]
![image](https://user-images.githubusercontent.com/3909535/207619456-e15bcbd8-f05f-4fd6-8981-1d0059205ecc.png)

**Comment by burnout87** [comment]
It loked like for me it was opened correctly

![image](https://user-images.githubusercontent.com/3757833/207620476-ed18ec93-4165-4ba1-86e4-569fe3a01e6a.png)

**Comment by volodymyrss** [comment]
it could be that it fails for previously requested queries. 
how would those be handled?

**Comment by burnout87** [comment]
> it could be that it fails for previously requested queries. how would those be handled?

Simply new branch is created, since now we calculate also the hash of the notebook content, new branches will be checked for existence and if needed created

**Comment by volodymyrss** [comment]
does this work for you:

https://renkulab.io/projects/astronomy/mmoda/mmoda-request/sessions/new?autostart=1&branch=mmoda_request_c570580ab66720b3_76adbfd3aecd840a&commit=8507b7803d4b67d7d77c305e5568c00cc11307ec&notebook=api_code_c570580ab66720b3.ipynb&env[ODA_TOKEN]=secret

**Comment by burnout87** [comment]
It opens for me...
![image](https://user-images.githubusercontent.com/3757833/207625530-441391f0-2cda-4bdc-9556-6788bba1122d.png)

**Comment by volodymyrss** [comment]
should it even open.

**Comment by burnout87** [comment]
> can you try in fresh browser session, private mode? does not work for me. It's possible renku tracks sessions somehow else?..

Tried and I managed to get it asking me for a token. Then I logged in (while being on the same private session), and it worked...could that be?

**Comment by volodymyrss** [comment]
> > can you try in fresh browser session, private mode? does not work for me. It's possible renku tracks sessions somehow else?..
> 
> Tried and I managed to get it asking me for a token. Then I logged in (while being on the same private session), and it worked...could that be?

yes, that may be it. 
But the repository is public, right?
Seems like a renku side issue?

Could you cross check this hypothesis (it's hard for me on the meeting), in a variety of conditions?.. Note that renku session list is tracked with cookies, so new private session is needed for each check. It might be that removing some arguments (filename, commit, env) makes a difference?..

**Comment by burnout87** [comment]
> > > can you try in fresh browser session, private mode? does not work for me. It's possible renku tracks sessions somehow else?..
> > 
> > 
> > Tried and I managed to get it asking me for a token. Then I logged in (while being on the same private session), and it worked...could that be?
> 
> yes, that may be it. But the repository is public, right? Seems like a renku side issue?
> 
> Could you cross check this hypothesis (it's hard for me on the meeting), in a variety of conditions?.. Note that renku session list is tracked with cookies, so new private session is needed for each check. It might be that removing some arguments (filename, commit, env) makes a difference?..

yes the repo is public

I just made few tests using a fresh new private session every time and interestingly, appareantly (cause it's hard to tell 100%), if the notebook to be opened is removed from the url ,then it works as expected

**Comment by volodymyrss** [comment]
> > > > can you try in fresh browser session, private mode? does not work for me. It's possible renku tracks sessions somehow else?..
> > > 
> > > 
> > > Tried and I managed to get it asking me for a token. Then I logged in (while being on the same private session), and it worked...could that be?
> > 
> > 
> > yes, that may be it. But the repository is public, right? Seems like a renku side issue?
> > Could you cross check this hypothesis (it's hard for me on the meeting), in a variety of conditions?.. Note that renku session list is tracked with cookies, so new private session is needed for each check. It might be that removing some arguments (filename, commit, env) makes a difference?..
> 
> yes the repo is public
> 
> I just made few tests using a fresh new private session every time and interestingly, appareantly (cause it's hard to tell 100%), if the notebook to be opened is removed from the url ,then it works as expected

this was my interpretation too. Should we make an issue for renku-ui, unless @rokroskar protests!

**Comment by rokroskar** [comment]
Thanks @burnout87!
