### ISSUE TITLE
Error while publishing to the Renku repository: Request data not found while view in renku?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#494]
why would this happen?

anything to add to sentry, unless there is?

![image](https://user-images.githubusercontent.com/3909535/207656715-efc4d416-27f8-4650-98c3-c805811c8dea.png)

**Comment by burnout87** [comment]
> why would this happen?
> 
> anything to add to sentry, unless there is?
> 

It's hard to reproduce the error, I am trying

**Comment by volodymyrss** [comment]
> > why would this happen?
> > anything to add to sentry, unless there is?
> 
> It's hard to reproduce the error, I am trying

when such an error is shown to the user, something should be sent to sentry, since it tells the user very little. User should be informed that internal error occurred (details quoted) and the dev are working on it.

**Comment by burnout87** [comment]
> > > why would this happen?
> > > anything to add to sentry, unless there is?
> > 
> > 
> > It's hard to reproduce the error, I am trying
> 
> when such an error is shown to the user, something should be sent to sentry, since it tells the user very little. User should be informed that internal error occurred (details quoted) and the dev are working on it.

Indeed I am really wondering why nothing arrive to sentry

**Comment by volodymyrss** [comment]
things arrive, most recently 4min ago, so it was not sent.

**Comment by burnout87** [comment]
> things arrive, most recently 4min ago, so it was not sent.

indeed, I was expecting something but nothing arrived

**Comment by volodymyrss** [comment]
so you may want to modify something

**Comment by burnout87** [comment]
In the meantime I am also implementing a different more generic message:

![image](https://user-images.githubusercontent.com/3757833/207667389-712dc91a-fe72-4c14-b000-8b9de487407a.png)

**Comment by burnout87** [comment]
> why would this happen?
> 
> anything to add to sentry, unless there is?
> 
> ![image](https://user-images.githubusercontent.com/3909535/207656715-efc4d416-27f8-4650-98c3-c805811c8dea.png)

BTW this was happening when the api_code was not found,and no sentry was sent in that case, with #495 I try to ceover also this case and others

**Comment by burnout87** [comment]
Intentionally sent a request excluding the job_id, and got the sentry!
