### ISSUE TITLE
restrict access to instruments by role

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#497]
in particular, development plugins should not be reported in instrument list, and should not be possible to query without special role ("oda workflow developer" or something like that)

@dsavchenko please protest if you already started work on this.

**Comment by burnout87** [comment]
Currently, the development instruments are returned if a certain env var is set, this is `DISPATCHER_DEBUG_MODE`.

Is this var set in production?

**Comment by volodymyrss** [comment]
I am not sure we are talking about the same thing. Please cite code which does this.

**Comment by volodymyrss** [comment]
Thanks. That's a dummy instrument, not a development instrument.

We need to distinguish some of the real instruments as development instruments, and only make them available to users with a special role.

**Comment by volodymyrss** [comment]
make them available both in dispatcher and frontend https://github.com/oda-hub/mmoda-frontend-module/issues/187

**Comment by burnout87** [comment]
> Thanks. That's a dummy instrument, not a development instrument.
> 
> We need to distinguish some of the real instruments as development instruments, and only make them available to users with a special role.

Is there some attribute of the instrument that can be inspected to understand if an instrument is a development one?

**Comment by volodymyrss** [comment]
> > Thanks. That's a dummy instrument, not a development instrument.
> > We need to distinguish some of the real instruments as development instruments, and only make them available to users with a special role.
> 
> Is there some attribute of the instrument that can be inspected to understand if it is a development one?

See my reply [just above ](https://github.com/oda-hub/dispatcher-app/issues/497#issuecomment-1370921530). We need to add it.

**Comment by burnout87** [comment]
> 
> @dsavchenko please protest if you already started work on this.

Please let me know if you had already started doing something in this respect. Otherwise I will start working on it.

**Comment by dsavchenko** [comment]
> Please let me know if you had already started doing something in this respect. Otherwise I will start working on it.

I didn't do it. Please start for the "static" instruments. Then I will adapt the nb2workflow plugin.

**Comment by volodymyrss** [comment]
This is needed to complete the current feature.  https://github.com/oda-hub/mmoda-frontend-module/issues/187 is also needed (but I understood from @motame  this is not complex). and also https://github.com/oda-hub/frontend-tab-generator - we saw it working, so it cannt be too far.

If we make progress on this before the next week's SmartSky meeting, it's a good indication we are well converging on SmartSky, and ready for it's further evolution.
