### ISSUE TITLE
In case of dossa errors, log file from processing should be copied to the session directory

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#50]
https://redmine.astro.unige.ch/issues/14820

**Comment by burnout87** [comment]
What is a dossa error? In case I can take care of this also

**Comment by volodymyrss** [comment]
this was copied from redmine, where there is also little explanation. It is a bit related to general exception handling (https://github.com/oda-hub/dispatcher-app/issues/25). Perhaps let's just close this one in favor of https://github.com/oda-hub/dispatcher-app/issues/25
