### ISSUE TITLE
error pushing to renku

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#515]
```python
WARNING:renku_helper:something happened while pushing the api_code: creating renku ini config file, 'renku "interactive"'
Traceback (most recent call last):
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/analysis/renku_helper.py", line 56, in push_api_code
    config_ini_obj = create_renku_ini_config_obj(repo, file_name)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/analysis/renku_helper.py", line 292, in create_renku_ini_config_obj
    renku_config['renku "interactive"']['default_url'] = f'/lab/tree/{default_url_file_name}'
  File "/pyenv/versions/3.8.5/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'renku "interactive"'
APIerror RequestNotUnderstood() constructor: Error while creating renku ini config file
INFO:renku_helper:==> removing repository folder, since it is no longer necessary
INFO:renku_helper:removing repo_working_dir_path=/tmp/mmoda-request4u00x4kw created for renku_repository_url=git@renkulab.io:astronomy/mmoda/mmoda-request.git
ERROR:root:Exception in push-renku-branch: RequestNotUnderstood(), Traceback (most recent call last):
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/analysis/renku_helper.py", line 56, in push_api_code
    config_ini_obj = create_renku_ini_config_obj(repo, file_name)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/analysis/renku_helper.py", line 292, in create_renku_ini_config_obj
    renku_config['renku "interactive"']['default_url'] = f'/lab/tree/{default_url_file_name}'
  File "/pyenv/versions/3.8.5/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'renku "interactive"'
```

**Comment by rokroskar** [comment]
It looks like [this change](https://github.com/SwissDataScienceCenter/renku-project-template/commit/f2a778119cb428f3c20e7399aedafabcc6973e43) has something to do with it

**Comment by volodymyrss** [comment]
> It looks like [this change](https://github.com/SwissDataScienceCenter/renku-project-template/commit/f2a778119cb428f3c20e7399aedafabcc6973e43) has something to do with it

it does look like it, but we do not use these templates, we start from here https://renkulab.io/gitlab/astronomy/mmoda/mmoda-request . But there it is also just `[interactive]` so I do not know, let's see with @burnout87 . Probably we can support both for now, I am just going to do this [hotfix](https://github.com/oda-hub/dispatcher-app/pull/516) if it looks "ok", and then we see, which is the way?

Anyway, how do we keep track of possibly breaking changes from renku side? We need to read release notes carefully I suppose, are they always there?

**Comment by burnout87** [comment]
> > It looks like [this change](https://github.com/SwissDataScienceCenter/renku-project-template/commit/f2a778119cb428f3c20e7399aedafabcc6973e43) has something to do with it
> 
> it does look like it, but we do not use these templates, we start from here https://renkulab.io/gitlab/astronomy/mmoda/mmoda-request . But there it is also just `[interactive]` so I do not know, let's see with @burnout87 . Probably we can support both for now, I am just going to do this [hotfix](https://github.com/oda-hub/dispatcher-app/pull/516) if it looks "ok", and then we see, which is the way?
> 

Supporting both probably won't be too difficult. Has it always been with `[interactive]`?

**Comment by rokroskar** [comment]
> it does look like it, but we do not use these templates

Then I'm not sure why this ever worked before :) 

> Anyway, how do we keep track of possibly breaking changes from renku side?

Yes we try to be pretty detailed / consistent in the release notes.

**Comment by volodymyrss** [comment]
> > it does look like it, but we do not use these templates
> 
> Then I'm not sure why this ever worked before :)

we even showed it on smartsky meetings several times, most recently last time.

I suspect we have different renku.ini in different branches now
 
> > Anyway, how do we keep track of possibly breaking changes from renku side?
> 
> Yes we try to be pretty detailed / consistent in the release notes.

if it's not too much trouble, could you show, for example, how this change was announced? So we can know how we should prepare

**Comment by rokroskar** [comment]
Honestly this one is quite an old change (the issue in the template repo that asked for it to be changed was from 2021) and it's something that is considered internal to the renku CLI so I'm not sure if it would have been documented somewhere...

**Comment by burnout87** [comment]
My guess is that the test project I use was initially created with the `[renku 'interactive']` entry.

And then updated, but I never applied this update.

**Comment by volodymyrss** [comment]
> My guess is that the test project I use was initially created with the `[renku 'interactive']` entry.
> 
> And then updated, but I never applied this update.

yes, but it was working recently because some branches are not recreated and keep the old value.

**Comment by volodymyrss** [comment]
> Honestly this one is quite an old change (the issue in the template repo that asked for it to be changed was from 2021) and it's something that is considered internal to the renku CLI so I'm not sure if it would have been documented somewhere...

Right, that's my concern: a change like that is too internal and is not guaranteed to be announced. But it would break our integration - with a delayed effect, since it only affects new repositories.

Anyway, we can add a live regression test for this situation, we do not have one yet.

**Comment by rokroskar** [comment]
yes I realize this is sub-optimal - we are trying to figure out how to prevent this sort of thing in the future - possibly by having release-candidates and potentially providing some template GH actions to facilitate testing. If you have suggestions on how to improve, let us know!

**Comment by volodymyrss** [comment]
> yes I realize this is sub-optimal - we are trying to figure out how to prevent this sort of thing in the future - possibly by having release-candidates and potentially providing some template GH actions to facilitate testing. If you have suggestions on how to improve, let us know!

template GH actions sounds interesting. We'll need them to be triggered by renku release candidates, or just regularly?

**Comment by rokroskar** [comment]
My thinking was that it would be a cron that checks for releases. Usually we also make a release of renku-python (which is the relevant one here) a week or so before it hits a production instance, so there is some time buffer.

**Comment by volodymyrss** [comment]
yeah, we should test new releases of renku-python

our biggest problem here is that we do not test this part sufficiently, since we do not have a renku instance or fixture on which to test. here, the problem was not actually because of renku instance, just renku-python and state of our gitlab repository.

in principle, we could test against live renkulab.io and its gitlab

but if renkulab.io upgrades, how do we test against a release candidate?

**Comment by burnout87** [comment]
While working on #519 I created another test repository and, interestingly, this one was created with the section `renku 'interactive'` within its `renku.ini` file. 

Perhaps I selected an older version during the creation. But I am not sure, do you have an explanation for this @rok ?

Project seems to be at the latest version (Latest Renku Version | 1.10.0 , Latest Template Version 0.3.5 ).
