### ISSUE TITLE
exposing of the sentry token

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/dispatcher-app#52]
_cdci_data_analysis/config_dir/conf_env.yml_ and _tests/test-conf.yaml_ contain sentry url
if it is real, it obviously should not be public

If these files are needed for automatic testing (as far as I understand, they are) we should use github-secret of smth

**Comment by burnout87** [comment]
Such a key is removed here:
[https://github.com/oda-hub/dispatcher-app/blob/4c744c78dab2ef105228c45530a31bb9956b5513/cdci_data_analysis/flask_app/app.py#L204](https://github.com/oda-hub/dispatcher-app/blob/4c744c78dab2ef105228c45530a31bb9956b5513/cdci_data_analysis/flask_app/app.py#L204)

So not to be exposed when an exception occurs

**Comment by volodymyrss** [comment]
it's not real since it was moved into github. And absolutely, you are right, it should never have been there, it was a mistake.
