### ISSUE TITLE
sentry is currently not sent

### ISSUE THREAD

**Issue by burnout87** [oda-hub/dispatcher-app#523]
at least to @burnout87 , especially important for the gallery development

**Comment by volodymyrss** [comment]
if it's not sent, it's up to dispatcher.

Some messages are delivered

![image](https://user-images.githubusercontent.com/3909535/220978139-5e8199ae-f838-46b3-a202-930e98ed4195.png)


Can you login in sentry.io?

**Comment by burnout87** [comment]
Yes I can login in sentry.io, but nothign has arrived from the dispatcher, related to the gallery, but it should be

**Comment by burnout87** [comment]
We can close this after #577
