### ISSUE TITLE
Make site-specific email data configurable

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/dispatcher-app#540]
There is TODO, but it's not implemented, I believe
https://github.com/oda-hub/dispatcher-app/blob/74e260a4ad87df1c1fcc62a2b43578b82fb4e82d/cdci_data_analysis/analysis/email_helper.py#L333

There is also 'possibly-non-site-specific-link' placeholder in the emails. It's weird, even as default.

@volodymyrss @burnout87 who can do this changes efficiently? It's related to multi-site, so it could be on me, but I haven't yet touched email-related parts in the dispatcher.

**Comment by volodymyrss** [comment]
@burnout87 added this, could you have a look?

**Comment by burnout87** [comment]
ok it does not look to be a big change, it's a matter of extending the configuration
