### ISSUE TITLE
-use_gunicorn flag does not really imply using of gunicorn

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/dispatcher-app#55]
-use_gunicorn flag in https://github.com/oda-hub/dispatcher-app/blob/master/bin/run_osa_cdci_server.py does not really imply using of gunicorn
Flask development server is starting instead

The proposed fix is analogous to the https://github.com/dsavchenko/antares-backend/commit/dd88d123819860b59e69a59924d6b8996fc2998a

 This bug could be present in other backends. (Here I see it in https://github.com/oda-hub/magic-backend)

**Comment by volodymyrss** [comment]
yeah, a bit of a messy part. Do you think you could implement the proposed fix?

**Comment by dsavchenko** [comment]
> yeah, a bit of a messy part. Do you think you could implement the proposed fix?

ok, I will do

**Comment by volodymyrss** [comment]
thanks!
