### ISSUE TITLE
unable to open downloaded data product

### ISSUE THREAD

**Issue by andriineronov** [oda-hub/dispatcher-app#555]
I've produced a Fermi/LAT spectrum at staging.odahub.fr and clicked on the "download" button for PNG picture. It gives "product.tar.gz" that has something wrong in it:

<img width="610" alt="image" src="https://github.com/oda-hub/dispatcher-app/assets/27765790/ed7d30f1-4df2-4ca8-ae03-615eb1411525">

**Comment by dsavchenko** [comment]
Please try `mv product.tar product.png`

**Comment by dsavchenko** [comment]
> Please try `mv product.tar product.png`

@andriineronov  it's most probably the case. If yes, please confirm by closing this issue

We will track it in https://github.com/oda-hub/dispatcher-plugin-nb2workflow/issues/64
