### ISSUE TITLE
`http://oda-dispatcher:8000 is not a valid url` got from /call_back

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/dispatcher-app#558]
Just received it in Sentry. This never happened before.

`UserError  /call_back`

```
UserError: http://oda-dispatcher:8000 is not a valid url. 
A valid url should be like `https://www.astro.unige.ch/mmoda/dispatch-data`, you might verify if, for example, a valid schema is provided, i.e. url should start with http:// or https:// .
Please check it and try to issue again the request
```

**Comment by dsavchenko** [comment]
@volodymyrss @burnout87 any ideas?

**Comment by volodymyrss** [comment]
any more info, which site even?

**Comment by dsavchenko** [comment]
It's obviously in the French instance (I don't have others connected to my Sentry account). 

The request looks legitimate

<h5 class="app-19idom e9vbrbe1">Query String</h5>

| | |
-- | -- 
action | done
file_name | job_monitor.json
instrument_name | fermi
job_id | f68d919839198bb3
session_id | MYD95576HWPDVD4E
time_original_request | 1689608438.0057309
token | [Filtered]
work_dir | scratch_sid_MYD95576HWPDVD4E_jid_f68d919839198bb3

Dispatcher container is running for 42h, no such issues before

**Comment by volodymyrss** [comment]
> It's obviously in the French instance (I don't have others connected to my Sentry account).

oh but we connected different people to our collective sentries at different time, you might have suddenly gotten a message.

> The request looks legitimate
> ##### Query String
> 	
> action 	done
> file_name 	job_monitor.json
> instrument_name 	fermi
> job_id 	f68d919839198bb3
> session_id 	MYD95576HWPDVD4E
> time_original_request 	1689608438.0057309
> token 	[Filtered]
> work_dir 	scratch_sid_MYD95576HWPDVD4E_jid_f68d919839198bb3
> 
> Dispatcher container is running for 42h, no such issues before

this exception must be somewhere in the code. By the way I do not seem to get "ready" emails so maybe "ready" callback always fails with some similar exception. Then it's strange you only got the alert one. Do you get ready emails from this instance?

**Comment by volodymyrss** [comment]
please refer to the issue and to where @burnout87 noticed it.

**Comment by dsavchenko** [comment]
Here https://github.com/oda-hub/dispatcher-app/issues/553#issuecomment-1634351796_

**Comment by burnout87** [comment]
I noticed a weird behavior on the staging dispatcher, in particular completion emails for images are not sent. Whereas for light curves and spectra, behavior is as expected.

**Comment by dsavchenko** [comment]
This is fixed by https://github.com/oda-hub/oda_api/pull/220
