### ISSUE TITLE
time overflow

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#561]
https://cdci.sentry.io/issues/4308331873/?project=1467382&query=is%3Aunresolved&referrer=issue-stream&stream_index=0

https://github.com/oda-hub/dispatcher-app/blob/cb5b4f5a8b0bda29832f4f7cd5a6053256a6b31a/cdci_data_analysis/analysis/email_helper.py#L192

**Comment by burnout87** [comment]
overflow happens here:

https://github.com/oda-hub/dispatcher-app/blob/cb5b4f5a8b0bda29832f4f7cd5a6053256a6b31a/cdci_data_analysis/analysis/email_helper.py#L52

**Comment by burnout87** [comment]
The expected `timestamp` input of `datetime.fromtimestamp` has to be in seconds ((POSIX timestamp) such as is returned by [time.time()](https://docs.python.org/3/library/time.html#time.time)). So probably one in milliseconds was provided

**Comment by volodymyrss** [comment]
> The expected `timestamp` input of `datetime.fromtimestamp` has to be in seconds ((POSIX timestamp) such as is returned by [time.time()](https://docs.python.org/3/library/time.html#time.time)). So probably one in milliseconds was provided

Where would it come from in milliseconds? See however above I quote where the time of first request is derived, it's not a safe way. Maybe a check on validity of time can be added right there. And a better way to derive the time.

**Comment by burnout87** [comment]
> > The expected `timestamp` input of `datetime.fromtimestamp` has to be in seconds ((POSIX timestamp) such as is returned by [time.time()](https://docs.python.org/3/library/time.html#time.time)). So probably one in milliseconds was provided
> 
> Where would it come from in milliseconds? See however above I quote where the time of first request is derived, it's not a safe way. Maybe a check on validity of time can be added right there. And a better way to derive the time.

It is hard to tell. What you quoted is one way the time is derived, but it might not be the only one. Although it is probably the way it was in this specific instance. So, a proper check on the validity is a good idea.

**Comment by burnout87** [comment]
Re-opening since it was noticed again during a notebook execution:
`[ DispatcherException: timestamp out of range for platform time_t ]`

**Comment by burnout87** [comment]
An issue with the token I was using was triggering the error, it can be closed now.
