### ISSUE TITLE
 product type jemx_image not in query_dictionary

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#564]
Someone made a request for JEM-X image, but got the following error message:

Error 400, Bad Request: [ InstrumentQueryBackEnd : isgri ] constructor failed: product type jemx_image not in query_dictionary {'isgri_image': 'isgri_image_query', 'isgri_spectrum': 'isgri_spectrum_query', 'isgri_lc': 'isgri_lc_query', 'spectral_fit': 'spectral_fit_query'}

We should send a sentry in this case to see the issue

**Comment by burnout87** [comment]
I guess it is not this one:

https://cdci.sentry.io/issues/4414972235/?project=1467382&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=0

Even though it looks very similar
