### ISSUE TITLE
if no "done" callback received in some large delay, 30min, try to re-submit the request

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#566]

**Comment by burnout87** [comment]
* check the status reading the `job_monitor` json file
* if not `done`, and not `failed`, check the last time it was modified
  * if this time > 30 min, resubmit

Questions:
* to be performed during a `run_analysis` call ?
* resubmit a `run_analysis` request ?
  * would this trigger a `done` callback ?

**Comment by burnout87** [comment]
does it make sense as a sequence of steps?

**Comment by volodymyrss** [comment]
> * check the status reading the `job_monitor` json file
> 
>     * if not `done`, and not `failed`, check the last time it was modified
>       * if this time > 30 min, resubmit

yes

> 
> Questions:
> 
>     * to be performed during a `run_analysis` call ?
> 
>     * resubmit a `run_analysis` request ?

yes

>       * would this trigger a `done` callback ?

it might also just return the product
