### ISSUE TITLE
prevent aliasing between different users.

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#59]

**Comment by burnout87** [comment]
An idea could be to simply consider the user ID extracted from the token, in the creation of the jobID

**Comment by burnout87** [comment]
sure

**Comment by volodymyrss** [comment]
oh I thought that token can contain expiration data and so. Maybe only used ID can be extracted for the purposes of job_id generation?

**Comment by burnout87** [comment]
I was actually thinking the same. Only the ID should work for us

**Comment by volodymyrss** [comment]
this one, on the other hand, has a potential (even if small) to compromise some of the key policies on data rights, so it's critical. Luckily, if I understand correctly, it is quite simple.

**Comment by burnout87** [comment]
Tackled within #62
