### ISSUE TITLE
make default matrix room id configurable

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#603]
getting "sending matrix message failed matrix room_id not available"
let's make default come from config

**Comment by burnout87** [comment]
the `room_id` is user dependent, is where the message will be sent to, it will have to be part of the token

or do we want to be able to send a message to more rooms, beside the user one?

**Comment by burnout87** [comment]
ok, as first, I will implement a `Bcc`-style approach, and see how that goes

**Comment by volodymyrss** [comment]
most importantly, we do not need error if user token has matrix configuration. reasonable default should not lead to sentry exception
