### ISSUE TITLE
run_query() got an unexpected keyword argument 'return_progress'

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#637]
![image](https://github.com/oda-hub/dispatcher-app/assets/3909535/41783cbc-1e11-47f7-8766-b5bacdbc80f9)

**Comment by burnout87** [comment]
where did this happen? in production?
can you share some more details?

**Comment by volodymyrss** [comment]
on production. please try it yourself.

**Comment by burnout87** [comment]
I have made several tests, on production, and could not reproduce it

**Comment by volodymyrss** [comment]
do you click the fit button?

**Comment by burnout87** [comment]
> do you click the fit button?

could reproduce it, that is the detail I needed

**Comment by volodymyrss** [comment]
> > do you click the fit button?
> 
> could reproduce it, that is the detail I needed

in the original screenshot, it says "spectral_fit" which points to this. But ok, so we confirm.

**Comment by volodymyrss** [comment]
I suppose it's related to latest dispatcher release https://gitlab.astro.unige.ch/oda/dispatcher/dispatcher-chart/-/commits/v-22.11.0025

I thought it'd be backward compatible, but I guess in this special case it is not.

**Comment by burnout87** [comment]
I managed to reproduce it also locally, I will have a better look
