### ISSUE TITLE
problem if token is None

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#64]
in the current deployment, experienced this:

```python
exception in run_analysis: %s %s TypeError("argument of type 'NoneType' is not iterable") Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cdci_data_analysis/flask_app/app.py", line 247, in run_analysis
    r = query.run_query(disp_conf=app.config['conf'])
  File "/usr/local/lib/python3.8/site-packages/cdci_data_analysis/flask_app/dispatcher_query.py", line 1254, in run_query
    mail_sending_job_submitted = tokenHelper.get_token_user_submitted_email(self.decoded_token)
  File "/usr/local/lib/python3.8/site-packages/cdci_data_analysis/analysis/tokenHelper.py", line 33, in get_token_user_submitted_email
    return decoded_token['mssub'] if 'mssub' in decoded_token else None
TypeError: argument of type 'NoneType' is not iterable
```
while client receives 

```python
...
`error_message": "argument of type \'NoneType\' is not iterable`
...
```

apart from the bug itself, a problem with this situation is that user receives a message user should not receive, and exception does not arrive in sentry.

**Comment by burnout87** [comment]
Did you run a specific test ? So I can reproduce it

**Comment by volodymyrss** [comment]
this is the outcome of a "standard" integration test which was run:

https://in.odahub.io/odatests/data?uri=http%3A%2F%2Fddahub.io%2Fontology%2Fdata%23data-67ec1eb30373bc8e

this is the test workflow itself:

https://in.odahub.io/odatests/workflow?uri=http%3A//odahub.io/ontology%23test_image_2scw_recent_isgri_yearplusold_multiosa_7601f0ce

this is the location of the code:

https://github.com/volodymyrss/oda_test_kit/blob/7601f0ce/test_image.py#L49

I suppose this situation should be included in an async unit test. I think it happens while constructing job_id when token is not set (is None). 
Does the traceback show it?

**Comment by burnout87** [comment]
I think I already spot the bug. It is trying to send an email (and in particular extract token-related info) when it is not supposed to, since the request is public so no information on whom the email should be sent.

And yes, it is material for an async test.
