### ISSUE TITLE
Attempting to call `Job.get_latest_monitor_mtime()` while this method is defined only in `OsaJob`

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/dispatcher-app#643]
I encountered this problem once when playing with nb2workflow instrument. Can't reproduce it every time. 
@burnout87 do you have any insights?

**Comment by burnout87** [comment]
mmm I would have to look at it closely to understand where and why it happens

**Comment by burnout87** [comment]
this happens because the `get_latest_monitor_mtime` has been defined for the `OsaJob` class instead that for the parent class `Job`. I missed when working on #585

**Comment by dsavchenko** [comment]
I needed to quickle fix it anyway, so https://github.com/oda-hub/dispatcher-app/pull/648
