### ISSUE TITLE
With non-integral instruments, even if the job_status is set to "progress" it gets reset to "submitted"

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/dispatcher-app#645]
E.g. here https://github.com/oda-hub/dispatcher-plugin-nb2workflow/blob/54e1e1507ab685c77d4c967d21ead6958cfa1ead/dispatcher_plugin_nb2workflow/dataserver_dispatcher.py#L229, we set status "progress" if backend returns "running". 
But the dispatcher always responds with "submitted".

This could affect both types of progress reporting

**Comment by burnout87** [comment]
here it's where the status is set to `submitted`

https://github.com/oda-hub/dispatcher-app/blob/e8f5b28e1f99f40e6efced9e438cc93a11d878cf/cdci_data_analysis/flask_app/dispatcher_query.py#L2110-L2137
