### ISSUE TITLE
Email sending exception affects callback processing

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/dispatcher-app#665]
If an exception occurs in email sending during processing the "status=progress" callback, the status is not set. 
(The done status seems to be set properly )

(Encountered this in stanging where the admin user has dummy email address and by mailing platform is blocking it, responding with error status)

We have to catch the exception somewhere so that other code can continue

@burnout87 I think you know best both parts (setting status, sending emails) so I will assign you.

**Comment by burnout87** [comment]
At the current state, during a call_back, the email is not sent if the status is `progress`. the check is performed here:

https://github.com/oda-hub/dispatcher-app/blob/617110283afddc6e862f0156c5a32d9af3cae62b/cdci_data_analysis/analysis/email_helper.py#L693-L771

is it possible to have an example of the call_back request the triggers the exception?

**Comment by dsavchenko** [comment]
> At the current state, during a call_back, the email is not sent if the status is `progress`.

That's weird then. I will then try to explore further and invent some test or example.
It's a bit complicated to do, as it depends on the state and requires some (fake?) smtp server

**Comment by burnout87** [comment]
> > At the current state, during a call_back, the email is not sent if the status is `progress`.
> 
> That's weird then. I will then try to explore further and invent some test or example. It's a bit complicated to do, as it depends on the state and requires some (fake?) smtp server

I developed a simple local mail server to use as a fixture for the testing, maybe it helps?

https://github.com/oda-hub/dispatcher-app/blob/617110283afddc6e862f0156c5a32d9af3cae62b/cdci_data_analysis/pytest_fixtures.py#L237C5-L316

**Comment by dsavchenko** [comment]
Finally, seems that I was wrong. The logs were mixed-up. This email error was from other callback.

Still, the "progress" status seems to not being set (though, I see in the logs that the callback is passed, I see it in the logs) with the first callback (which is by default in nb2service). If there are report_progress() in cells, it works then (the example of "sleeping" product of nb2w-example). I added a sleep into the "lightcurve" product of this instrument to demonstrate the behaviour. Probably some race condition?

I'm closing this issue as misleading

**Comment by burnout87** [comment]
> 
> Still, the "progress" status seems to not being set (though, I see in the logs that the callback is passed) with the first callback (which is by default in nb2service). 

You mean that nb2servoice does not send the call_back with the proper status, or is the dispatcher that is not setting the status properly during the `run_call_back` function ?

**Comment by dsavchenko** [comment]
> You mean that nb2servoice does not send the call_back with the proper status, or is the dispatcher that is not setting the status properly during the `run_call_back` function ?

The dispatcher is not setting it. There is `run_call_back` invocation in the logs, but finally, the status is "submitted".

I suspect that there is some race condition. Dispatcher is running in several independent processes (via gunicorn). And the job monitor is file-based. So it could be that if this callback is processed too early by a neighbouring process, the status gets overwritten by the process that's processing the first run_analysis request. 
This is just a guess.

We should probably open an Issue. Maybe after some additional investigation
