### ISSUE TITLE
test token provided by legacy dispatcher

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#67]

**Comment by burnout87** [comment]
Didn't realized that I had already covered this case:

[https://github.com/oda-hub/dispatcher-app/blob/8e979a1cf102635733dfc59174b69ae084813667/tests/test_job_management.py#L90-L91](https://github.com/oda-hub/dispatcher-app/blob/8e979a1cf102635733dfc59174b69ae084813667/tests/test_job_management.py#L90-L91)

**Comment by volodymyrss** [comment]
ok good
