### ISSUE TITLE
sometimes dispatcher creates two directories for the job_id

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#677]
currently the user gets the error

but we want that a sentry alert should be sent

and the user should get "internal error, we are working on it"

**Comment by burnout87** [comment]
some of those issues on sentry:

https://cdci.sentry.io/issues/?project=1467382&query=is%3Aunresolved+message%3A%22Found+two+non+aliased+identical+job_id%22&referrer=issue-list&statsPeriod=30d
