### ISSUE TITLE
skip check `allowed_values`

### ISSUE THREAD

**Issue by burnout87** [oda-hub/dispatcher-app#707]
The parameter `column_name_MW_EBV` is set in the [notebook](https://gitlab.renkulab.io/gabriele.barni/photoz-euclid/-/blob/master/Run_Phosphoros_preComputedMG.ipynb) with `oda:allowed_value "" ;`.
By loading a fits file though, the list of values in the drop-down menu changes, and the user might want to select a value different from the empty string (only allowed value): if the user  does that, the dispatcher returns the error below

![image](https://github.com/user-attachments/assets/cf7e47f3-af36-41d0-9448-bf66c768e001)

Is there already a way to skip the check for the allowed_values?
Is a dedicated Parameter class or extra_metadata a better option?

**Comment by dsavchenko** [comment]
`oda:allowed_value '' ; ` means exactly: the only allowed value of a parameter is empty string. It just needs to be removed

**Comment by burnout87** [comment]
by removing the `allowed_value` attribute (which will generate an input selector), and transforming the input selector into a `select` (that will be the filled in), the value can be passed in the form
