### ISSUE TITLE
errors while posting to gallery

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#717]
Could you please have a look?

![image](https://github.com/user-attachments/assets/7e0bb04b-b8c3-4514-80eb-d11f840db804)

https://cdci.sentry.io/issues/6001643643/?alert_rule_id=723253&alert_timestamp=1729260188829&alert_type=email&environment=production&notification_uuid=84e096c9-1882-419e-b7c4-3b80f6e6954e&project=1467382&referrer=alert_email

**Comment by burnout87** [comment]
the gallery seems not to be reachable at all

**Comment by burnout87** [comment]
gallery is back online
