### ISSUE TITLE
When token is not valid scratch_dir is not created

### ISSUE THREAD

**Issue by burnout87** [oda-hub/dispatcher-app#88]
Is this an actual problem? 

Maybe not, but I would still have it created so that some useful content to be extracted

**Comment by burnout87** [comment]
@volodymyrss what do you think?

**Comment by volodymyrss** [comment]
definitely a problem. public requests should still work. actually, I am surprised, I thought I run public requests?..
could you please make a test that fails first to show and then fix?
tentatively classying as a bug.

**Comment by burnout87** [comment]
#89
