### ISSUE TITLE
`api/v1.0/oda/js9/js9plugins.js` returns 500

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#95]

**Comment by burnout87** [comment]
When does this happen?

**Comment by volodymyrss** [comment]
In frontend interaction. It should just return js, could you investigate?

**Comment by volodymyrss** [comment]
you can access there, try to request something, and follow network calls when you pick js9: http://frontend.staging.odahub.io/cdci/astrooda/

**Comment by burnout87** [comment]
Are the following files supposed to be dynamically generated? Or provided within the dispatcher app?

- oda/js9/js9support.css
- /js9/js9.css
- /js9/js9.min.js
- /js9/js9support.min.js
- /js9/js9plugins.js
- /js9/js9prefs.js
- /js9/js9support.min.js
- /js9/js9.min.js
- /js9/js9plugins.js

**Comment by burnout87** [comment]
They're not found when rendering the html output of the `get_js9_plot`  call.

**Comment by volodymyrss** [comment]
All I can tell you is that JS9 is this thing https://github.com/ericmandel/js9/
Otherwise I am mostly investigating just as you would.

It's clear they are static content, see here:

https://github.com/oda-hub/dispatcher-app/blob/master/cdci_data_analysis/flask_app/app.py#L331

I would follow install instruction there https://github.com/ericmandel/js9/ and try to make it work locally first. And also make a test.
We can also ask Andrea, but we will need a repeatable installation.

If it seems too much out of what you are doing now, maybe let me do it, and concentrate instead on further API role tests - those are important.

**Comment by burnout87** [comment]
At least we both saw that what is missing is the installation of a library

**Comment by volodymyrss** [comment]
it is working, but serving static files should be done differently, currently I made an ugly patch. There should be a config option to location js9 static files.
